In [157]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import oracledb
import cx_Oracle
import seaborn as sns
import sqlalchemy
from sqlalchemy import create_engine

<h1>회원의 카테고리 선택 현황에 따른 추천</h1>
<h4>카테고리가 겹치는 인원만 체크해서 탐색시간 감축 </h4>
<h4>사용자가 읽었던 기사 종류를 토대로 회원들 간 유사도 측정</h4>
<h4>DB에서 로그테이블, 카테고리 선택 테이블, 뉴스테이블 획득 </h4>
<h4>테스트 데이터는 모든 회원이 자신이 선택한 카테고리의 기사만 읽음</h4>

In [158]:
# 1. target에 현재 회원 id 저장
target = str(3)

In [174]:
# 2. 카테고리가 겹치는 회원의 색출
# 2 - 1) DB에서 prefrence 테이블 호출 및 데이터프레임으로 변환
engine = create_engine('oracle://ist:ist@localhost:1521/xe')
con = engine.connect()

query = "SELECT mem_id, cate_id FROM test_pref"
pref_data = pd.read_sql_query(query, con)
print(pref_data)

    mem_id cate_id
0        1      정치
1        1   생활/문화
2        1      사회
3        2      연예
4        2      사회
..     ...     ...
745    249      정치
746    249   생활/문화
747    250      정치
748    250      사회
749    250      연예

[750 rows x 2 columns]

In [175]:
# 2 - 2) 회원별 선택한 카테고리 피벗 테이블화
usr_category_pivot = pref_data.pivot_table(index = 'mem_id', columns = 'cate_id', aggfunc = len, fill_value = 0)
usr_category_pivot

cate_id  IT/과학  경제  사회  생활/문화  세계  연예  정치
mem_id
1            0   0   1      1   0   0   1
10           0   0   0      1   0   1   1
100          0   0   0      1   1   1   0
101          0   0   1      0   1   0   1
102          1   0   1      1   0   0   0
...        ...  ..  ..    ...  ..  ..  ..
95           0   0   0      1   0   1   1
96           0   0   0      0   1   1   1
97           0   0   0      1   0   1   1
98           0   0   1      0   1   1   0
99           0   0   1      0   0   1   1

[250 rows x 7 columns]

In [176]:
# 2 - 3) target 회원과 카테고리가 겹치는 유저 색출
target_cate = set(usr_category_pivot.columns[usr_category_pivot.loc[str(target)] == 1])
print("%s 번 회원의 카테고리 : " %(target), target_cate)
print("카테고리가 2개 이상 겹치는 회원 목록")
same_cate_users = set()
for mid, row in usr_category_pivot.iterrows():
    other = set(usr_category_pivot.columns[row == 1])
    if len(target_cate.intersection(other)) >= 2:  # 2개 이상 겹칠 때만 
        same_cate_users.add(mid)
        print(mid, ":", other)
print(same_cate_users)

3 번 회원의 카테고리 :  {'사회', '생활/문화', 'IT/과학'}
카테고리가 2개 이상 겹치는 회원 목록
1 : {'생활/문화', '정치', '사회'}
102 : {'사회', '생활/문화', 'IT/과학'}
111 : {'경제', '생활/문화', '사회'}
115 : {'사회', '정치', 'IT/과학'}
121 : {'세계', '사회', 'IT/과학'}
122 : {'연예', '사회', 'IT/과학'}
124 : {'연예', '사회', 'IT/과학'}
125 : {'연예', '생활/문화', 'IT/과학'}
128 : {'경제', '사회', 'IT/과학'}
129 : {'연예', '생활/문화', 'IT/과학'}
13 : {'생활/문화', '정치', 'IT/과학'}
130 : {'세계', '사회', 'IT/과학'}
131 : {'경제', '생활/문화', '사회'}
132 : {'세계', '생활/문화', 'IT/과학'}
134 : {'경제', '생활/문화', 'IT/과학'}
136 : {'연예', '생활/문화', '사회'}
14 : {'생활/문화', '정치', 'IT/과학'}
150 : {'연예', '사회', 'IT/과학'}
153 : {'세계', '사회', 'IT/과학'}
155 : {'사회', '생활/문화', 'IT/과학'}
158 : {'생활/문화', '정치', 'IT/과학'}
159 : {'세계', '생활/문화', 'IT/과학'}
162 : {'세계', '생활/문화', '사회'}
165 : {'생활/문화', '정치', 'IT/과학'}
169 : {'경제', '사회', 'IT/과학'}
17 : {'경제', '사회', 'IT/과학'}
171 : {'세계', '생활/문화', '사회'}
176 : {'연예', '생활/문화', '사회'}
178 : {'경제', '사회', 'IT/과학'}
179 : {'세계', '사회', 'IT/과학'}
183 : {'세계', '생활/문화', '사회'}
184 : {'연예', '생활/문화', 'IT/과학'}
185 : {'연예', '생활/문화', 'IT/과학'}
189 : {'경제', '생활/문화', '사회'}
19 : {'경제', '사회', 'IT/과학'}
190 : {'연예', '사회', 'IT/과학'}
191 : {'세계', '생활/문화', 'IT/과학'}
192 : {'경제', '사회', 'IT/과학'}
193 : {'연예', '생활/문화', 'IT/과학'}
195 : {'세계', '생활/문화', 'IT/과학'}
196 : {'연예', '생활/문화', 'IT/과학'}
198 : {'사회', '생활/문화', 'IT/과학'}
2 : {'연예', '생활/문화', '사회'}
203 : {'세계', '생활/문화', 'IT/과학'}
204 : {'연예', '생활/문화', '사회'}
208 : {'사회', '정치', 'IT/과학'}
209 : {'연예', '사회', 'IT/과학'}
210 : {'세계', '생활/문화', 'IT/과학'}
212 : {'경제', '생활/문화', 'IT/과학'}
213 : {'연예', '생활/문화', '사회'}
216 : {'생활/문화', '정치', 'IT/과학'}
218 : {'연예', '생활/문화', 'IT/과학'}
22 : {'사회', '생활/문화', 'IT/과학'}
221 : {'연예', '사회', 'IT/과학'}
222 : {'세계', '생활/문화', 'IT/과학'}
223 : {'생활/문화', '정치', '사회'}
224 : {'세계', '사회', 'IT/과학'}
225 : {'생활/문화', '정치', 'IT/과학'}
226 : {'생활/문화', '정치', '사회'}
227 : {'사회', '생활/문화', 'IT/과학'}
228 : {'세계', '생활/문화', 'IT/과학'}
229 : {'세계', '생활/문화', 'IT/과학'}
232 : {'생활/문화', '정치', '사회'}
233 : {'연예', '사회', 'IT/과학'}
234 : {'생활/문화', '정치', 'IT/과학'}
239 : {'세계', '생활/문화', '사회'}
24 : {'경제', '생활/문화', 'IT/과학'}
241 : {'생활/문화', '정치', '사회'}
242 : {'연예', '사회', 'IT/과학'}
245 : {'경제', '생활/문화', '사회'}
247 : {'사회', '생활/문화', 'IT/과학'}
29 : {'경제', '생활/문화', '사회'}
3 : {'사회', '생활/문화', 'IT/과학'}
30 : {'사회', '생활/문화', 'IT/과학'}
31 : {'세계', '생활/문화', 'IT/과학'}
33 : {'경제', '생활/문화', '사회'}
34 : {'연예', '사회', 'IT/과학'}
42 : {'연예', '생활/문화', '사회'}
43 : {'사회', '정치', 'IT/과학'}
45 : {'세계', '사회', 'IT/과학'}
46 : {'연예', '생활/문화', 'IT/과학'}
49 : {'세계', '생활/문화', 'IT/과학'}
55 : {'연예', '사회', 'IT/과학'}
60 : {'연예', '사회', 'IT/과학'}
64 : {'사회', '정치', 'IT/과학'}
65 : {'연예', '사회', 'IT/과학'}
70 : {'사회', '생활/문화', 'IT/과학'}
73 : {'사회', '정치', 'IT/과학'}
74 : {'사회', '정치', 'IT/과학'}
79 : {'세계', '생활/문화', '사회'}
8 : {'사회', '정치', 'IT/과학'}
80 : {'경제', '사회', 'IT/과학'}
85 : {'세계', '생활/문화', 'IT/과학'}
86 : {'연예', '생활/문화', '사회'}
89 : {'경제', '생활/문화', 'IT/과학'}
9 : {'연예', '사회', 'IT/과학'}
90 : {'사회', '생활/문화', 'IT/과학'}
92 : {'세계', '사회', 'IT/과학'}
94 : {'연예', '사회', 'IT/과학'}
{'34', '30', '165', '1', '134', '131', '3', '239', '92', '46', '102', '17', '190', '247', '121', '64', '184', '24', '155', '229', '218', '19', '192', '212', '73', '111', '8', '9', '176', '242', '196', '185', '222', '125', '80', '45', '94', '227', '86', '178', '60', '183', '169', '122', '22', '213', '115', '33', '2', '70', '74', '203', '65', '224', '245', '124', '49', '132', '130', '128', '225', '221', '209', '85', '31', '79', '42', '43', '129', '159', '226', '13', '198', '153', '216', '150', '191', '241', '232', '193', '228', '210', '195', '171', '29', '89', '14', '233', '234', '158', '208', '162', '204', '179', '223', '55', '136', '189', '90'}

In [177]:
# 3. target과 유사한 유저 판별
# 3 - 1) DB에서 유저 로그 호출
query = "SELECT mem_id, cate_id, news_id FROM user_log"
log_data = pd.read_sql_query(query, con)
log_data

      mem_id cate_id news_id
0        166      연예    1294
1         10      연예    1294
2        108      연예    1294
3         83      연예    1294
4         98      연예    1294
...      ...     ...     ...
15995     48      경제     227
15996    149      경제     227
15997    173      경제     227
15998    144      경제     227
15999     63      경제     227

[16000 rows x 3 columns]

In [190]:
# 3 - 2) 카테고리가 2개이상 겹치는 회원만 필트링
log_data = log_data[log_data['mem_id'].isin(same_cate_users)]
log_data

      mem_id cate_id news_id
5        221      연예    1294
9        213   생활/문화     620
10       125   생활/문화     620
12       176   생활/문화     620
13       171   생활/문화     620
...      ...     ...     ...
15989     64   IT/과학    1108
15990     65   IT/과학    1108
15991    227   IT/과학    1108
15993    150   IT/과학    1108
15994    245      경제     227

[6399 rows x 3 columns]

In [205]:
# 3 - 3) 회원 피벗 테이블로 변경
log_pivot = log_data.pivot_table(index='mem_id', columns=['cate_id', 'news_id'], aggfunc=len, fill_value=0)
log_pivot

cate_id IT/과학                                               ... 정치           \
news_id  1000 1001 1002 1003 1004 1005 1006 1007 1008 1009  ... 87 88 89  9
mem_id                                                      ...
1           0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
102         0    0    1    0    0    0    0    0    0    0  ...  0  0  0  0
111         0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
115         0    0    1    0    0    0    0    0    0    0  ...  0  0  0  0
121         0    1    0    0    0    1    0    0    0    0  ...  0  0  0  0
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... .. .. .. ..
89          0    0    0    0    0    0    0    1    1    0  ...  0  0  0  0
9           0    0    0    0    0    0    0    1    1    0  ...  0  0  0  0
90          1    0    0    0    0    0    0    0    0    1  ...  0  0  0  0
92          0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
94          0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0

cate_id
news_id 93 94 95 96 97 99
mem_id
1        0  0  1  0  0  0
102      0  0  0  0  0  0
111      0  0  0  0  0  0
115      1  1  0  0  0  0
121      0  0  0  0  0  0
...     .. .. .. .. .. ..
89       0  0  0  0  0  0
9        0  0  0  0  0  0
90       0  0  0  0  0  0
92       0  0  0  0  0  0
94       0  0  0  0  0  0

[99 rows x 1310 columns]

In [244]:
# 3 - 4) 회원 별 코사인 유사도 계산
cos_sim = cosine_similarity(log_pivot, log_pivot)
user_similarity = pd.DataFrame(data = cos_sim, index = log_pivot.index, columns = log_pivot.index)
print("코사인 유사도\n", user_similarity)

코사인 유사도
 mem_id         1       102       111       115       121       122       124  \
mem_id
1       1.000000  0.030528  0.061056  0.027592  0.014097  0.026158  0.000000
102     0.030528  1.000000  0.068966  0.077916  0.031846  0.044319  0.062776
111     0.061056  0.068966  1.000000  0.015583  0.111463  0.029546  0.000000
115     0.027592  0.077916  0.015583  1.000000  0.043176  0.040057  0.056739
121     0.014097  0.031846  0.111463  0.043176  1.000000  0.109150  0.043483
...          ...       ...       ...       ...       ...       ...       ...
89      0.041984  0.047422  0.047422  0.057149  0.014599  0.027089  0.028778
9       0.027400  0.046424  0.015475  0.097904  0.057166  0.159111  0.140859
90      0.069471  0.062776  0.062776  0.028370  0.057977  0.080684  0.071429
92      0.000000  0.072836  0.091045  0.032915  0.151351  0.046806  0.082874
94      0.030528  0.034483  0.017241  0.031166  0.015923  0.147731  0.015694

mem_id       125       128       129  ...        79         8        80  \
mem_id                                ...
1       0.000000  0.014202  0.025367  ...  0.105939  0.110900  0.015397
102     0.046105  0.048125  0.071634  ...  0.085473  0.055674  0.052176
111     0.015368  0.048125  0.014327  ...  0.034189  0.013918  0.052176
115     0.013890  0.043497  0.025898  ...  0.046352  0.100639  0.015719
121     0.028387  0.074076  0.026463  ...  0.047363  0.141398  0.032125
...          ...       ...       ...  ...       ...       ...       ...
89      0.084541  0.117660  0.039406  ...  0.047019  0.063804  0.031891
9       0.041380  0.100785  0.064293  ...  0.030686  0.137414  0.031220
90      0.041967  0.058408  0.130410  ...  0.062242  0.038008  0.047494
92      0.000000  0.084709  0.015131  ...  0.072216  0.102897  0.110208
94      0.030737  0.096250  0.057307  ...  0.034189  0.069592  0.017392

mem_id        85        86        89         9        90        92        94
mem_id
1       0.039487  0.013700  0.041984  0.027400  0.069471  0.000000  0.030528
102     0.044603  0.139272  0.047422  0.046424  0.062776  0.072836  0.034483
111     0.029735  0.077373  0.047422  0.015475  0.062776  0.091045  0.017241
115     0.067188  0.027973  0.057149  0.097904  0.028370  0.032915  0.031166
121     0.096116  0.057166  0.014599  0.057166  0.057977  0.151351  0.015923
...          ...       ...       ...       ...       ...       ...       ...
89      0.068155  0.000000  1.000000  0.042563  0.043167  0.033389  0.047422
9       0.093408  0.055556  0.042563  1.000000  0.070430  0.049029  0.092848
90      0.040600  0.056344  0.043167  0.070430  1.000000  0.082874  0.047082
92      0.078509  0.016343  0.033389  0.049029  0.082874  1.000000  0.072836
94      0.044603  0.046424  0.047422  0.092848  0.047082  0.072836  1.000000

[99 rows x 99 columns]

In [211]:
# 4. 추천할 기사 n개 출력
# 4 - 1) 기사 별 추천점수 계산
sel_cate_recommend = {} # 선택 카테고리의 기사
non_sel_cate_recommend = {} # 미선택 카테고리의 기사

# 만약 유사도가 높은 상위 n명만 반영하고 싶으면 아래 for문 위아래로 코드 추가
# n = 0
# for user in log_pivot.index:
#     n -= 1
#     if n == 0: break
print(target_cate)
for user in log_pivot.index:
    if user == target: continue  # 자기 자신은 제외
    score = user_similarity.at[str(target), str(user)]
    # 두 회원의 유사도를 점수로 활용 -> 유사도가 높은 회원이 읽은 기사가 추천 될 확률 증가

    for nid in log_pivot.columns:
        if log_pivot.at[user, nid] == 1 and log_pivot.at[target, nid] == 0: # target이 안봤고, user가 봤으면
            title = list(nid)  # [카테고리, 뉴스 ID]
            if title[0] in target_cate:
                if nid not in sel_cate_recommend:
                    sel_cate_recommend[title[1]] = score
                else :
                    sel_cate_recommend[title[1]] += score
            else:
                if nid not in non_sel_cate_recommend:
                    non_sel_cate_recommend[title[1]] = score
                else :
                    non_sel_cate_recommend[title[1]] += score

# 테스트 출력
print("선택 카테고리 추천 기사")
print(list(sel_cate_recommend.keys())[:5])
print("미선택 카테고리 추천 기사")
print(list(non_sel_cate_recommend.keys())[:5])

{'사회', '생활/문화', 'IT/과학'}
선택 카테고리 추천 기사
['400', '415', '433', '472', '504']
미선택 카테고리 추천 기사
['108', '112', '12', '122', '148']

In [212]:
# 4 - 2) DB에서 기사 테이블 호출
query = "SELECT news_id, cate_id, title FROM test_news"
news = pd.read_sql_query(query, con)
news

     news_id cate_id                                    title
0        296      경제        "살던 집 팔아 잔금 치러야 하는데…" 속타는 입주 예정자들
1        297      경제   에코프로 주가 하락에 뿔난 투자자… "불법 공매도 근절, 전산화해야"
2        298      경제  가계빚 한달 만에 6조8000억 폭증에도 정부 "주담대 안정, 긍정적"
3        299      경제          “괜히 돈만 썼다”…일회용품 규제 철회 두고 ‘와글와글’
4        300      경제                  고공행진 엔비디아 주가, 조만간 꺼진다?
...      ...     ...                                      ...
1389    1389      연예                              김영,"훈훈한 미소"
1390    1390      연예                            신연서,"소중한 강아지"
1391    1391      연예                              최훈재,"나도 찰칵"
1392    1392      연예                              백서빈,"깔끔 청년"
1393    1393      연예                             구상범 감독,"볼하트"

[1394 rows x 3 columns]

In [222]:
# 4 - 3) 선택/미선택 카테고리 기사 리스트 데이터프레임화
sel_res = dict(sorted(sel_cate_recommend.items(), key=lambda x : -x[1]))
non_sel_res = dict(sorted(non_sel_cate_recommend.items(), key=lambda x : -x[1]))

# 결과에 제목 띄우기 위해 news 테이블과 join
sel_news_id = pd.DataFrame({"news_id" : sel_res.keys()})
result_sel = pd.merge(sel_news_id, news, on="news_id")
result_sel.head(5)

  news_id cate_id                                        title
0     516      사회                          철원서 집단 전세사기 의심사례 발생
1    1141   IT/과학               美 정부, 군사용 반도체 생산 위해 인텔에 5조원 투자
2     447      사회         항공사 수하물 운반 직원이 귀중품 절도…4천만 원짜리 가방도 빼내
3     405      사회         "긴 꼬리 살랑, 서울 지하철에 웬 쥐가"…퇴근하던 시민 "깜짝"
4    1003   IT/과학  ‘적자 늪’ 탈출한 CJ ENM, 작지만 소중한 74억원…“자회사 손실 줄어”

In [223]:
# 미선택 카테고리에 대한 추천 결과가 필요하면 아래 코드 주석 해제
# non_sel_news_id = pd.DataFrame({"news_id" : non_sel_res.keys()})
# result_non_sel = pd.merge(non_sel_news_id, news, on="news_id")
# result_non_sel.head(5)

  news_id cate_id                                      title
0      60      정치  류호정 “이준석 함께? 오히려 좋아”…선그은 비명계, ‘설화’ 빚는 이준석
1      95      정치        대통령실, 김대기 비서실장 재산신고 누락 논란에 “단순한 실수”
2     114      정치  “옆방서 20분이나 뒷담화” 이준석이 밝힌 ‘안철수씨 조용히 합시다’ 전말
3       1      정치      이준석 “영남 정치인들 편하게 놔두지 않겠다”…영남 신당 추진 시사
4     133      정치                 "선거제 개편" 핵심은?…이탄희 의원에게 듣는다

In [224]:
# 4 - 4) 최종 출력
print("" + str(target) + "번 회원님, 다음 기사를 추천합니다.")
print(f'{target}번 회원의 선택 카테고리 : ', target_cate)
result_sel.head(20)  # <-- 필요한 갯수만큼

3번 회원님, 다음 기사를 추천합니다.
3번 회원의 선택 카테고리 :  {'사회', '생활/문화', 'IT/과학'}

   news_id cate_id                                              title
0      516      사회                                철원서 집단 전세사기 의심사례 발생
1     1141   IT/과학                     美 정부, 군사용 반도체 생산 위해 인텔에 5조원 투자
2      447      사회               항공사 수하물 운반 직원이 귀중품 절도…4천만 원짜리 가방도 빼내
3      405      사회               "긴 꼬리 살랑, 서울 지하철에 웬 쥐가"…퇴근하던 시민 "깜짝"
4     1003   IT/과학        ‘적자 늪’ 탈출한 CJ ENM, 작지만 소중한 74억원…“자회사 손실 줄어”
5     1115   IT/과학              5G·LTE 요금제 교차가입, 저가 요금·단말 확대로 통신비 줄인다
6     1166   IT/과학                ‘성병’ 걸린 아기 11배 늘었다…“상황이 심각” 어느 정도길래
7      410      사회                   "야구 보기 참 힘드네…" 온라인 세상 속 소외되는 노인들
8      474      사회               마약수사 무마" 양현석 항소심에서 징역형 집행유예...무죄 뒤집혀
9     1157   IT/과학                            양자소재로 초저전력 ‘스핀 반도체’ 만든다
10     463      사회                      낚싯줄에 걸린 마약주사기 추적…‘여장 남자’까지 검거
11     534      사회                      외국인 유흥업소서 마약파티… 판매·유통책 무더기 검거
12    1189   IT/과학  SKT 3Q 영업익 7%↑ 4980억원…"통신·신사업 고른 성장…AI 전략 고도화"...
13    1162   IT/과학               위메이드 "2024년은 대작 출시의 해...미르4·M은 中 출시"
14     573      사회           뉴스타파 "방심위, 정권 가이드라인 따르다 뒤늦게 법적 한계 깨달은 것"
15     426      사회                 노소영 측 “아트센터 퇴거 못 해…이혼한다고 이렇게까지 하나”
16     421      사회          ‘사옥 퇴거 소송’ SK 계열사에…노소영 측 “이혼한다고 이렇게까지” 울분
17     702   생활/문화                           입동, 일교차 극심‥내일 오후 전국 가끔 비
18     577      사회               "갓길로 나와주세요! 막지 말고" 구급차 호소하자 오히려 "헉?"
19     601   생활/문화                   서울 지하철 총파업 가능성…"내일 출근 대란 오나" 초긴장

In [268]:
# 추천 점수 체크
test = dict(sorted(sel_cate_recommend.items(), key=lambda x: -x[1]))
for k,v in test.items():
    print(k, ':', v)

516 : 0.17888543819998312
1141 : 0.17888543819998312
447 : 0.17888543819998312
405 : 0.17888543819998312
1003 : 0.17888543819998312
1115 : 0.17888543819998312
1166 : 0.17888543819998312
410 : 0.17888543819998312
474 : 0.17888543819998312
1157 : 0.17888543819998312
463 : 0.17888543819998312
534 : 0.17888543819998312
1189 : 0.17888543819998312
1162 : 0.17888543819998312
573 : 0.17888543819998312
426 : 0.17888543819998312
421 : 0.16705381391691132
702 : 0.16705381391691132
577 : 0.15430334996209188
601 : 0.15430334996209188
666 : 0.15430334996209188
776 : 0.15430334996209188
778 : 0.15430334996209188
462 : 0.15430334996209188
503 : 0.15430334996209188
670 : 0.15430334996209188
417 : 0.15430334996209188
507 : 0.15430334996209188
565 : 0.15430334996209188
1170 : 0.15430334996209188
491 : 0.15430334996209188
1032 : 0.15430334996209188
1151 : 0.15430334996209188
528 : 0.15430334996209188
1140 : 0.15430334996209188
689 : 0.15430334996209188
795 : 0.15430334996209188
1038 : 0.15430334996209188
571 : 0.15430334996209188
1094 : 0.15430334996209188
740 : 0.15430334996209188
749 : 0.15430334996209188
755 : 0.15430334996209188
1089 : 0.15430334996209188
734 : 0.15430334996209188
1009 : 0.15430334996209188
1088 : 0.15430334996209188
609 : 0.15430334996209188
736 : 0.15430334996209188
1074 : 0.15430334996209188
1000 : 0.15430334996209188
1098 : 0.15430334996209188
1059 : 0.15430334996209188
1184 : 0.15430334996209188
785 : 0.15430334996209188
589 : 0.15430334996209188
1150 : 0.15430334996209188
556 : 0.15430334996209188
604 : 0.15430334996209188
1195 : 0.15430334996209188
747 : 0.14301938838683884
1124 : 0.14085904245475275
465 : 0.14085904245475275
541 : 0.14085904245475275
1106 : 0.14085904245475275
522 : 0.14085904245475275
1154 : 0.14085904245475275
1035 : 0.14085904245475275
1128 : 0.14085904245475275
1108 : 0.14085904245475275
543 : 0.12524485821702988
660 : 0.12385842357671555
766 : 0.12385842357671555
783 : 0.12385842357671555
521 : 0.12385842357671555
628 : 0.12385842357671555
716 : 0.12385842357671555
574 : 0.12385842357671555
1192 : 0.10366105360784114
435 : 0.10366105360784114
550 : 0.10366105360784114
559 : 0.10366105360784114
425 : 0.10366105360784114
523 : 0.10366105360784114
1015 : 0.10366105360784114
1060 : 0.10366105360784114
402 : 0.10366105360784114
538 : 0.10366105360784114
1114 : 0.10366105360784114
476 : 0.10366105360784114
519 : 0.10366105360784114
431 : 0.10366105360784114
542 : 0.10366105360784114
1142 : 0.10259783520851543
1159 : 0.10259783520851543
1066 : 0.10259783520851543
1023 : 0.10259783520851543
1070 : 0.10259783520851543
485 : 0.10259783520851543
1041 : 0.10259783520851543
1025 : 0.10259783520851543
1061 : 0.10259783520851543
1039 : 0.10259783520851543
489 : 0.10259783520851543
445 : 0.10259783520851543
1138 : 0.10259783520851543
437 : 0.10259783520851543
514 : 0.10259783520851543
1093 : 0.10259783520851543
1077 : 0.10259783520851543
544 : 0.10259783520851543
1096 : 0.10259783520851543
432 : 0.10259783520851543
415 : 0.10084389681792214
588 : 0.10084389681792214
999 : 0.10084389681792214
1174 : 0.10084389681792214
1055 : 0.10084389681792214
595 : 0.10084389681792214
1064 : 0.10084389681792214
1073 : 0.10084389681792214
1165 : 0.10084389681792214
576 : 0.10084389681792214
1118 : 0.10084389681792214
1131 : 0.10084389681792214
532 : 0.10084389681792214
1020 : 0.10084389681792214
636 : 0.09682458365518541
679 : 0.09682458365518541
453 : 0.09682458365518541
564 : 0.09682458365518541
1126 : 0.09682458365518541
1175 : 0.09682458365518541
1013 : 0.09682458365518541
1075 : 0.09682458365518541
792 : 0.09682458365518541
668 : 0.09682458365518541
790 : 0.09682458365518541
1010 : 0.09682458365518541
1068 : 0.09682458365518541
1133 : 0.09682458365518541
1137 : 0.09682458365518541
659 : 0.09682458365518541
667 : 0.09682458365518541
720 : 0.09682458365518541
727 : 0.09682458365518541
789 : 0.09682458365518541
411 : 0.09682458365518541
698 : 0.09682458365518541
706 : 0.09682458365518541
715 : 0.09682458365518541
681 : 0.09682458365518541
1085 : 0.09682458365518541
1030 : 0.09682458365518541
583 : 0.09682458365518541
1065 : 0.09682458365518541
424 : 0.09682458365518541
704 : 0.09682458365518541
691 : 0.09579159651319533
1050 : 0.08885233166386383
450 : 0.08885233166386383
1084 : 0.08885233166386383
483 : 0.08885233166386383
446 : 0.08885233166386383
1004 : 0.08885233166386383
1176 : 0.0877058019307029
735 : 0.08714893406611901
448 : 0.08714893406611901
529 : 0.08714893406611901
653 : 0.08714893406611901
777 : 0.08660254037844385
610 : 0.08660254037844385
629 : 0.08660254037844385
461 : 0.08660254037844385
683 : 0.08660254037844385
607 : 0.07864837576396144
719 : 0.07864837576396144
744 : 0.07864837576396144
775 : 0.07864837576396144
645 : 0.07864837576396144
770 : 0.07864837576396144
429 : 0.07864837576396144
700 : 0.07864837576396144
711 : 0.07864837576396144
674 : 0.07864837576396144
649 : 0.07864837576396144
684 : 0.07864837576396144
533 : 0.07607257743127308
460 : 0.07607257743127308
1057 : 0.07607257743127308
1097 : 0.07607257743127308
1112 : 0.07607257743127308
1121 : 0.07607257743127308
441 : 0.07607257743127308
1110 : 0.07607257743127308
1196 : 0.07607257743127308
515 : 0.07607257743127308
1111 : 0.07607257743127308
1139 : 0.07607257743127308
512 : 0.07607257743127308
1007 : 0.07607257743127308
1172 : 0.07607257743127308
1187 : 0.07607257743127308
591 : 0.07607257743127308
1156 : 0.07607257743127308
1101 : 0.07607257743127308
1152 : 0.07607257743127308
414 : 0.07607257743127308
492 : 0.07607257743127308
1008 : 0.07607257743127308
546 : 0.07607257743127308
509 : 0.07607257743127308
608 : 0.07554973565193743
791 : 0.07172191381865586
1109 : 0.07161148740394328
1158 : 0.07161148740394328
407 : 0.07161148740394328
563 : 0.07161148740394328
525 : 0.07161148740394328
540 : 0.07161148740394328
1040 : 0.07161148740394328
1149 : 0.07161148740394328
1119 : 0.07161148740394328
464 : 0.07161148740394328
479 : 0.07161148740394328
1031 : 0.07161148740394328
501 : 0.07161148740394328
1180 : 0.07161148740394328
1062 : 0.07161148740394328
1197 : 0.07161148740394328
1105 : 0.07161148740394328
406 : 0.07161148740394328
451 : 0.07161148740394328
1069 : 0.07161148740394328
505 : 0.07161148740394328
1026 : 0.07161148740394328
478 : 0.07161148740394328
592 : 0.07161148740394328
1086 : 0.07161148740394328
1045 : 0.07161148740394328
622 : 0.07085252515814196
612 : 0.07085252515814196
708 : 0.07085252515814196
728 : 0.07085252515814196
443 : 0.07042952122737638
594 : 0.07042952122737638
695 : 0.07042952122737638
527 : 0.07042952122737638
520 : 0.07042952122737638
717 : 0.07042952122737638
763 : 0.07042952122737638
547 : 0.07042952122737638
693 : 0.07042952122737638
517 : 0.07042952122737638
780 : 0.07042952122737638
615 : 0.07042952122737638
640 : 0.06722926454528143
692 : 0.06722926454528143
705 : 0.06722926454528143
539 : 0.06722926454528143
619 : 0.06722926454528143
639 : 0.06722926454528143
743 : 0.06722926454528143
638 : 0.06722926454528143
473 : 0.06722926454528143
555 : 0.06722926454528143
597 : 0.06722926454528143
416 : 0.06722926454528143
686 : 0.06722926454528143
709 : 0.06722926454528143
739 : 0.06722926454528143
477 : 0.06722926454528143
750 : 0.06722926454528143
457 : 0.06722926454528143
618 : 0.06722926454528143
694 : 0.06722926454528143
616 : 0.06722926454528143
551 : 0.06722926454528143
585 : 0.06722926454528143
732 : 0.06722926454528143
580 : 0.06722926454528143
781 : 0.06722926454528143
623 : 0.06722926454528143
759 : 0.06722926454528143
466 : 0.06722926454528143
452 : 0.06722926454528143
495 : 0.06722926454528143
1043 : 0.06693494407520822
1135 : 0.06693494407520822
723 : 0.06693494407520822
687 : 0.06693494407520822
553 : 0.06693494407520822
567 : 0.06693494407520822
600 : 0.06506000486323553
418 : 0.06405126152203486
484 : 0.06405126152203486
1178 : 0.061721339984836754
784 : 0.061721339984836754
753 : 0.059234887775909226
648 : 0.058470534620468605
657 : 0.058470534620468605
714 : 0.058470534620468605
787 : 0.058470534620468605
1136 : 0.058470534620468605
631 : 0.058470534620468605
1120 : 0.058470534620468605
1090 : 0.058470534620468605
1132 : 0.058470534620468605
1153 : 0.058470534620468605
1051 : 0.058470534620468605
1082 : 0.058470534620468605
1183 : 0.058470534620468605
641 : 0.058470534620468605
647 : 0.058470534620468605
655 : 0.058470534620468605
752 : 0.058470534620468605
1047 : 0.058470534620468605
713 : 0.058470534620468605
665 : 0.058470534620468605
746 : 0.058470534620468605
796 : 0.058470534620468605
669 : 0.058470534620468605
1046 : 0.058470534620468605
1092 : 0.058470534620468605
630 : 0.058470534620468605
603 : 0.058470534620468605
771 : 0.058470534620468605
671 : 0.058470534620468605
725 : 0.058470534620468605
676 : 0.058470534620468605
701 : 0.058470534620468605
779 : 0.058470534620468605
621 : 0.058470534620468605
1076 : 0.058470534620468605
1022 : 0.05773502691896257
500 : 0.05773502691896257
1072 : 0.05773502691896257
1033 : 0.05773502691896257
586 : 0.05773502691896257
1083 : 0.05773502691896257
620 : 0.057377531054924685
682 : 0.057377531054924685
493 : 0.057377531054924685
632 : 0.057377531054924685
712 : 0.057377531054924685
652 : 0.057377531054924685
518 : 0.057377531054924685
794 : 0.057377531054924685
738 : 0.05668202012651357
480 : 0.05668202012651357
1028 : 0.05668202012651357
1001 : 0.05504818825631802
1144 : 0.05504818825631802
1116 : 0.05504818825631802
436 : 0.05504818825631802
1016 : 0.05504818825631802
1036 : 0.05504818825631802
513 : 0.05504818825631802
510 : 0.05504818825631802
526 : 0.05473805515039733
1005 : 0.05473805515039733
1185 : 0.05473805515039733
439 : 0.05473805515039733
458 : 0.05473805515039733
498 : 0.05473805515039733
511 : 0.05473805515039733
535 : 0.05473805515039733
1054 : 0.05473805515039733
454 : 0.05473805515039733
506 : 0.05473805515039733
494 : 0.05473805515039733
1011 : 0.05473805515039733
1190 : 0.05473805515039733
486 : 0.05473805515039733
419 : 0.05473805515039733
530 : 0.05473805515039733
409 : 0.05473805515039733
1179 : 0.05473805515039733
558 : 0.05473805515039733
537 : 0.051298917604257706
762 : 0.051298917604257706
1182 : 0.050854762771560764
496 : 0.048038446141526144
718 : 0.04767312946227961
624 : 0.04767312946227961
675 : 0.0469668218313862
1002 : 0.0469668218313862
1037 : 0.0469668218313862
726 : 0.0469668218313862
642 : 0.0469668218313862
1171 : 0.0469668218313862
1161 : 0.0469668218313862
1145 : 0.0469668218313862
768 : 0.0469668218313862
611 : 0.0469668218313862
1063 : 0.0469668218313862
614 : 0.0469668218313862
1125 : 0.0469668218313862
651 : 0.0469668218313862
1168 : 0.0469668218313862
605 : 0.0469668218313862
1100 : 0.046291004988627565
468 : 0.046291004988627565
1017 : 0.046291004988627565
482 : 0.046291004988627565
1198 : 0.046291004988627565
449 : 0.046291004988627565
1148 : 0.046291004988627565
1067 : 0.046291004988627565
531 : 0.04596385597769216
471 : 0.04596385597769216
1173 : 0.04564354645876384
696 : 0.04564354645876384
606 : 0.04564354645876384
757 : 0.04564354645876384
1042 : 0.04564354645876384
730 : 0.04564354645876384
1014 : 0.044426165831931916
1181 : 0.044426165831931916
782 : 0.044136741475237475
433 : 0.03546634510659543
472 : 0.03546634510659543
646 : 0.03546634510659543
1113 : 0.03546634510659543
1080 : 0.03546634510659543
1117 : 0.03546634510659543
1129 : 0.03546634510659543
420 : 0.03390317518104051
536 : 0.03390317518104051
557 : 0.03390317518104051
455 : 0.03390317518104051
633 : 0.03390317518104051
773 : 0.03390317518104051
760 : 0.03390317518104051
733 : 0.03390317518104051
627 : 0.03178208630818641
678 : 0.03178208630818641
1099 : 0.03178208630818641
1194 : 0.03178208630818641
625 : 0.03178208630818641
613 : 0.03178208630818641
745 : 0.03178208630818641
599 : 0.03178208630818641
656 : 0.03178208630818641
729 : 0.031083493608010455
737 : 0.031083493608010455
788 : 0.031083493608010455
1018 : 0.031083493608010455
1053 : 0.031083493608010455
1164 : 0.031083493608010455
1078 : 0.031083493608010455
1122 : 0.031083493608010455
1160 : 0.031083493608010455
1177 : 0.031083493608010455
1107 : 0.031083493608010455
1052 : 0.031083493608010455
1147 : 0.031083493608010455
758 : 0.031083493608010455
602 : 0.031083493608010455
1034 : 0.031083493608010455
769 : 0.031083493608010455
774 : 0.031083493608010455
1186 : 0.031083493608010455
1188 : 0.031083493608010455
697 : 0.031083493608010455
793 : 0.031083493608010455
1146 : 0.031083493608010455
772 : 0.031083493608010455
710 : 0.031083493608010455
1044 : 0.031083493608010455
741 : 0.031083493608010455
724 : 0.031083493608010455
677 : 0.031083493608010455
654 : 0.031083493608010455
690 : 0.031083493608010455
469 : 0.030860669992418377
502 : 0.03042903097250923
637 : 0.03042903097250923
650 : 0.03042903097250923
685 : 0.03042903097250923
742 : 0.03042903097250923
487 : 0.03042903097250923
508 : 0.03042903097250923
593 : 0.03042903097250923
673 : 0.03042903097250923
403 : 0.03042903097250923
456 : 0.03042903097250923
572 : 0.03042903097250923
499 : 0.03042903097250923
688 : 0.03042903097250923
754 : 0.03042903097250923
767 : 0.03042903097250923
664 : 0.03042903097250923
751 : 0.03042903097250923
661 : 0.03042903097250923
524 : 0.03042903097250923
721 : 0.03042903097250923
748 : 0.03042903097250923
497 : 0.03042903097250923
731 : 0.03042903097250923
490 : 0.03042903097250923
634 : 0.03042903097250923
582 : 0.03042903097250923
707 : 0.029814239699997188
798 : 0.029814239699997188
459 : 0.029814239699997188
643 : 0.029814239699997188
703 : 0.029814239699997188
413 : 0.028867513459481284
488 : 0.028867513459481284
662 : 0.028688765527462343
566 : 0.027216552697590865
400 : 0.016951587590520255
504 : 0.016951587590520255
1193 : 0.016951587590520255
579 : 0.016951587590520255
554 : 0.016951587590520255
561 : 0.016951587590520255
422 : 0.016951587590520255
475 : 0.016951587590520255
481 : 0.016951587590520255
1019 : 0.016951587590520255
1130 : 0.016951587590520255
568 : 0.016951587590520255
587 : 0.016951587590520255
1079 : 0.016951587590520255
428 : 0.016951587590520255
434 : 0.016951587590520255
438 : 0.016951587590520255
549 : 0.016951587590520255
584 : 0.016951587590520255
412 : 0.016951587590520255
1155 : 0.016951587590520255
1169 : 0.016951587590520255
427 : 0.016951587590520255
552 : 0.016951587590520255
404 : 0.016951587590520255
467 : 0.016951587590520255
1127 : 0.016951587590520255
1027 : 0.016951587590520255
1058 : 0.016951587590520255
1191 : 0.016951587590520255
1167 : 0.016951587590520255
430 : 0.016951587590520255
786 : 0.016012815380508715
680 : 0.016012815380508715
1095 : 0.016012815380508715
765 : 0.016012815380508715
764 : 0.016012815380508715

In [270]:
user_similarity[user_similarity['mem_id'] == target].sort_values(ascending=False)

KeyError: 'mem_id'