In [18]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import oracledb
import cx_Oracle
import seaborn as sns
import sqlalchemy
from sqlalchemy import create_engine

<h1>회원의 카테고리 선택 현황에 따른 추천</h1>
<h4>카테고리가 겹치는 인원만 체크해서 탐색시간 감축 </h4>
<h4>사용자가 읽었던 기사 종류를 토대로 회원들 간 유사도 측정</h4>
<h4>DB에서 로그테이블, 카테고리 선택 테이블, 뉴스테이블 획득 </h4>
<h4>테스트 데이터는 모든 회원이 자신이 선택한 카테고리의 기사만 읽음</h4>

In [19]:
# 1. target에 현재 회원 id 저장
target = str(1)

In [20]:
# 2. 카테고리가 겹치는 회원의 색출
# 2 - 1) DB에서 prefrence 테이블 호출 및 데이터프레임으로 변환
engine = create_engine('oracle://ist:ist@localhost:1521/xe')
con = engine.connect()

query = "SELECT mem_id, cate_id FROM test_pref"
pref_data = pd.read_sql_query(query, con)
print(pref_data)

    mem_id cate_id
0        1      정치
1        1   생활/문화
2        1      사회
3        2      연예
4        2      사회
..     ...     ...
745    249      정치
746    249   생활/문화
747    250      정치
748    250      사회
749    250      연예

[750 rows x 2 columns]

In [21]:
# 2 - 2) 회원별 선택한 카테고리 피벗 테이블화
usr_category_pivot = pref_data.pivot_table(index = 'mem_id', columns = 'cate_id', aggfunc = len, fill_value = 0)
usr_category_pivot

cate_id  IT/과학  경제  사회  생활/문화  세계  연예  정치
mem_id
1            0   0   1      1   0   0   1
10           0   0   0      1   0   1   1
100          0   0   0      1   1   1   0
101          0   0   1      0   1   0   1
102          1   0   1      1   0   0   0
...        ...  ..  ..    ...  ..  ..  ..
95           0   0   0      1   0   1   1
96           0   0   0      0   1   1   1
97           0   0   0      1   0   1   1
98           0   0   1      0   1   1   0
99           0   0   1      0   0   1   1

[250 rows x 7 columns]

In [22]:
# 2 - 3) target 회원과 카테고리가 겹치는 유저 색출
target_cate = set(usr_category_pivot.columns[usr_category_pivot.loc[str(target)] == 1])
print("%s 번 회원의 카테고리 : " %(target), target_cate)
print("카테고리가 2개 이상 겹치는 회원 목록")
same_cate_users = set()
for mid, row in usr_category_pivot.iterrows():
    other = set(usr_category_pivot.columns[row == 1])
    if len(target_cate.intersection(other)) >= 2:  # 2개 이상 겹칠 때만 
        same_cate_users.add(mid)
        print(mid, ":", other)
print(same_cate_users)

1 번 회원의 카테고리 :  {'사회', '정치', '생활/문화'}
카테고리가 2개 이상 겹치는 회원 목록
1 : {'사회', '정치', '생활/문화'}
10 : {'정치', '연예', '생활/문화'}
101 : {'사회', '정치', '세계'}
102 : {'사회', 'IT/과학', '생활/문화'}
105 : {'사회', '정치', '세계'}
111 : {'사회', '생활/문화', '경제'}
115 : {'사회', 'IT/과학', '정치'}
126 : {'사회', '정치', '세계'}
13 : {'정치', 'IT/과학', '생활/문화'}
131 : {'사회', '생활/문화', '경제'}
133 : {'사회', '정치', '세계'}
136 : {'사회', '연예', '생활/문화'}
14 : {'정치', 'IT/과학', '생활/문화'}
142 : {'정치', '생활/문화', '세계'}
145 : {'사회', '연예', '정치'}
146 : {'정치', '생활/문화', '세계'}
149 : {'사회', '정치', '경제'}
151 : {'정치', '생활/문화', '경제'}
155 : {'사회', 'IT/과학', '생활/문화'}
158 : {'정치', 'IT/과학', '생활/문화'}
162 : {'사회', '생활/문화', '세계'}
165 : {'정치', 'IT/과학', '생활/문화'}
167 : {'사회', '연예', '정치'}
168 : {'사회', '정치', '세계'}
171 : {'사회', '생활/문화', '세계'}
176 : {'사회', '연예', '생활/문화'}
177 : {'정치', '생활/문화', '경제'}
183 : {'사회', '생활/문화', '세계'}
186 : {'정치', '생활/문화', '경제'}
189 : {'사회', '생활/문화', '경제'}
194 : {'정치', '연예', '생활/문화'}
198 : {'사회', 'IT/과학', '생활/문화'}
199 : {'정치', '생활/문화', '경제'}
2 : {'사회', '연예', '생활/문화'}
200 : {'사회', '정치', '세계'}
204 : {'사회', '연예', '생활/문화'}
205 : {'정치', '생활/문화', '세계'}
206 : {'정치', '생활/문화', '세계'}
208 : {'사회', 'IT/과학', '정치'}
21 : {'정치', '연예', '생활/문화'}
213 : {'사회', '연예', '생활/문화'}
214 : {'사회', '연예', '정치'}
216 : {'정치', 'IT/과학', '생활/문화'}
22 : {'사회', 'IT/과학', '생활/문화'}
220 : {'정치', '생활/문화', '세계'}
223 : {'사회', '정치', '생활/문화'}
225 : {'정치', 'IT/과학', '생활/문화'}
226 : {'사회', '정치', '생활/문화'}
227 : {'사회', 'IT/과학', '생활/문화'}
232 : {'사회', '정치', '생활/문화'}
234 : {'정치', 'IT/과학', '생활/문화'}
235 : {'정치', '연예', '생활/문화'}
238 : {'사회', '정치', '세계'}
239 : {'사회', '생활/문화', '세계'}
241 : {'사회', '정치', '생활/문화'}
245 : {'사회', '생활/문화', '경제'}
247 : {'사회', 'IT/과학', '생활/문화'}
249 : {'정치', '연예', '생활/문화'}
250 : {'사회', '연예', '정치'}
29 : {'사회', '생활/문화', '경제'}
3 : {'사회', 'IT/과학', '생활/문화'}
30 : {'사회', 'IT/과학', '생활/문화'}
33 : {'사회', '생활/문화', '경제'}
36 : {'사회', '정치', '경제'}
41 : {'정치', '생활/문화', '경제'}
42 : {'사회', '연예', '생활/문화'}
43 : {'사회', 'IT/과학', '정치'}
44 : {'사회', '정치', '세계'}
47 : {'사회', '연예', '정치'}
48 : {'사회', '정치', '경제'}
5 : {'정치', '생활/문화', '세계'}
50 : {'정치', '연예', '생활/문화'}
53 : {'사회', '정치', '세계'}
56 : {'사회', '연예', '정치'}
64 : {'사회', 'IT/과학', '정치'}
67 : {'사회', '정치', '세계'}
70 : {'사회', 'IT/과학', '생활/문화'}
72 : {'사회', '연예', '정치'}
73 : {'사회', 'IT/과학', '정치'}
74 : {'사회', 'IT/과학', '정치'}
76 : {'사회', '정치', '경제'}
79 : {'사회', '생활/문화', '세계'}
8 : {'사회', 'IT/과학', '정치'}
86 : {'사회', '연예', '생활/문화'}
87 : {'사회', '연예', '정치'}
88 : {'사회', '정치', '경제'}
90 : {'사회', 'IT/과학', '생활/문화'}
95 : {'정치', '연예', '생활/문화'}
97 : {'정치', '연예', '생활/문화'}
99 : {'사회', '연예', '정치'}
{'14', '198', '220', '86', '43', '158', '99', '73', '155', '56', '171', '33', '176', '44', '101', '235', '21', '74', '72', '29', '177', '87', '136', '36', '70', '225', '216', '41', '226', '205', '245', '111', '76', '8', '3', '247', '102', '249', '50', '53', '13', '239', '238', '241', '47', '64', '167', '79', '162', '30', '208', '67', '142', '214', '95', '10', '105', '186', '126', '189', '232', '90', '223', '1', '146', '194', '234', '183', '168', '250', '48', '115', '97', '5', '200', '145', '204', '227', '42', '151', '199', '88', '22', '2', '133', '131', '149', '206', '165', '213'}

In [23]:
# 3. target과 유사한 유저 판별
# 3 - 1) DB에서 유저 로그 호출
query = "SELECT mem_id, cate_id, news_id FROM user_log"
log_data = pd.read_sql_query(query, con)
log_data

      mem_id cate_id news_id
0        166      연예    1294
1         10      연예    1294
2        108      연예    1294
3         83      연예    1294
4         98      연예    1294
...      ...     ...     ...
15995     48      경제     227
15996    149      경제     227
15997    173      경제     227
15998    144      경제     227
15999     63      경제     227

[16000 rows x 3 columns]

In [24]:
# 3 - 2) 카테고리가 2개이상 겹치는 회원만 필터링
log_data = log_data[log_data['mem_id'].isin(same_cate_users)]
log_data

      mem_id cate_id news_id
1         10      연예    1294
6         50      연예    1294
9        213   생활/문화     620
12       176   생활/문화     620
13       171   생활/문화     620
...      ...     ...     ...
15989     64   IT/과학    1108
15991    227   IT/과학    1108
15994    245      경제     227
15995     48      경제     227
15996    149      경제     227

[5778 rows x 3 columns]

In [25]:
# 3 - 3) 회원 피벗 테이블로 변경
log_pivot = log_data.pivot_table(index='mem_id', columns=['cate_id', 'news_id'], aggfunc=len, fill_value=0)
log_pivot

cate_id IT/과학                                               ... 정치           \
news_id  1000 1001 1002 1003 1004 1005 1006 1007 1008 1009  ... 90 91 92 93
mem_id                                                      ...
1           0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
10          0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
101         0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
102         0    0    1    0    0    0    0    0    0    0  ...  0  0  0  0
105         0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... .. .. .. ..
88          0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
90          1    0    0    0    0    0    0    0    0    1  ...  0  0  0  0
95          0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
97          0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0
99          0    0    0    0    0    0    0    0    0    0  ...  0  0  0  0

cate_id
news_id 94 95 96 97 98 99
mem_id
1        0  1  0  0  0  0
10       0  0  0  0  0  0
101      0  1  0  1  0  0
102      0  0  0  0  0  0
105      0  0  0  0  0  0
...     .. .. .. .. .. ..
88       0  0  0  0  0  0
90       0  0  0  0  0  0
95       0  0  0  0  0  0
97       0  0  0  0  0  0
99       0  0  0  0  0  0

[90 rows x 1306 columns]

In [26]:
# 3 - 4) 회원 별 코사인 유사도 계산
cos_sim = cosine_similarity(log_pivot, log_pivot)
user_similarity = pd.DataFrame(data = cos_sim, index = log_pivot.index, columns = log_pivot.index)
print("코사인 유사도\n", user_similarity)

코사인 유사도
 mem_id         1        10       101       102       105       111       115  \
mem_id
1       1.000000  0.028837  0.059054  0.030528  0.090978  0.061056  0.027592
10      0.028837  1.000000  0.063010  0.016287  0.027735  0.016287  0.073601
101     0.059054  0.063010  1.000000  0.016676  0.042597  0.016676  0.075361
102     0.030528  0.016287  0.016676  1.000000  0.058722  0.068966  0.077916
105     0.090978  0.027735  0.042597  0.058722  1.000000  0.000000  0.053074
...          ...       ...       ...       ...       ...       ...       ...
88      0.000000  0.032296  0.066136  0.034189  0.043667  0.119662  0.077253
90      0.069471  0.059300  0.045538  0.062776  0.013363  0.062776  0.028370
95      0.042606  0.030307  0.000000  0.000000  0.081954  0.000000  0.014499
97      0.064984  0.083205  0.042597  0.000000  0.025000  0.058722  0.039806
99      0.031068  0.049725  0.050913  0.000000  0.044821  0.017547  0.079295

mem_id       126        13       131  ...        76        79         8  \
mem_id                                ...
1       0.049852  0.041984  0.130779  ...  0.041100  0.105939  0.110900
10      0.026596  0.014932  0.000000  ...  0.058471  0.032296  0.013148
101     0.136158  0.045867  0.000000  ...  0.119737  0.033068  0.094234
102     0.014078  0.094845  0.049240  ...  0.015475  0.085473  0.055674
105     0.119866  0.053838  0.013975  ...  0.039528  0.058222  0.047405
...          ...       ...       ...  ...       ...       ...       ...
88      0.083746  0.015673  0.048821  ...  0.092057  0.033898  0.027600
90      0.038443  0.057555  0.044821  ...  0.028172  0.062242  0.038008
95      0.026196  0.044122  0.106898  ...  0.014398  0.047715  0.051800
97      0.035960  0.026919  0.013975  ...  0.000000  0.014556  0.011851
99      0.028653  0.016087  0.050111  ...  0.078743  0.052192  0.056659

mem_id        86        87        88        90        95        97        99
mem_id
1       0.013700  0.000000  0.000000  0.069471  0.042606  0.064984  0.031068
10      0.087706  0.119262  0.032296  0.059300  0.030307  0.083205  0.049725
101     0.044901  0.034890  0.066136  0.045538  0.000000  0.042597  0.050913
102     0.139272  0.054109  0.034189  0.062776  0.000000  0.000000  0.000000
105     0.026352  0.046072  0.043667  0.013363  0.081954  0.025000  0.044821
...          ...       ...       ...       ...       ...       ...       ...
88      0.076715  0.053648  1.000000  0.046682  0.015905  0.014556  0.069589
90      0.056344  0.000000  0.046682  1.000000  0.014602  0.013363  0.047916
95      0.057591  0.067125  0.015905  0.014602  1.000000  0.177566  0.065302
97      0.131762  0.076787  0.014556  0.013363  0.177566  1.000000  0.074702
99      0.031497  0.055067  0.069589  0.047916  0.065302  0.074702  1.000000

[90 rows x 90 columns]

In [27]:
# 4. 추천할 기사 n개 출력
# 4 - 1) 기사 별 추천점수 계산
sel_cate_recommend = {} # 선택 카테고리의 기사
non_sel_cate_recommend = {} # 미선택 카테고리의 기사

# 만약 유사도가 높은 상위 n명만 반영하고 싶으면 아래 for문 위아래로 코드 추가
# n = 0
# for user in log_pivot.index:
#     n -= 1
#     if n == 0: break
print(target_cate)
for user in log_pivot.index:
    if user == target: continue  # 자기 자신은 제외
    score = user_similarity.at[str(target), str(user)]
    # 두 회원의 유사도를 점수로 활용 -> 유사도가 높은 회원이 읽은 기사가 추천 될 확률 증가

    for nid in log_pivot.columns:
        if log_pivot.at[user, nid] == 1 and log_pivot.at[target, nid] == 0: # target이 안봤고, user가 봤으면
            title = list(nid)  # [카테고리, 뉴스 ID]
            if title[0] in target_cate:
                if nid not in sel_cate_recommend:
                    sel_cate_recommend[title[1]] = score
                else :
                    sel_cate_recommend[title[1]] += score
            else:
                if nid not in non_sel_cate_recommend:
                    non_sel_cate_recommend[title[1]] = score
                else :
                    non_sel_cate_recommend[title[1]] += score

# 테스트 출력
print("선택 카테고리 추천 기사")
print(list(sel_cate_recommend.keys())[:5])
print("미선택 카테고리 추천 기사")
print(list(non_sel_cate_recommend.keys())[:5])

{'사회', '정치', '생활/문화'}
선택 카테고리 추천 기사
['603', '636', '645', '654', '663']
미선택 카테고리 추천 기사
['1200', '1206', '1207', '1209', '1214']

In [28]:
# 4 - 2) DB에서 기사 테이블 호출
query = "SELECT news_id, cate_id, title FROM test_news"
news = pd.read_sql_query(query, con)
news

     news_id cate_id                                    title
0        296      경제        "살던 집 팔아 잔금 치러야 하는데…" 속타는 입주 예정자들
1        297      경제   에코프로 주가 하락에 뿔난 투자자… "불법 공매도 근절, 전산화해야"
2        298      경제  가계빚 한달 만에 6조8000억 폭증에도 정부 "주담대 안정, 긍정적"
3        299      경제          “괜히 돈만 썼다”…일회용품 규제 철회 두고 ‘와글와글’
4        300      경제                  고공행진 엔비디아 주가, 조만간 꺼진다?
...      ...     ...                                      ...
1389    1389      연예                              김영,"훈훈한 미소"
1390    1390      연예                            신연서,"소중한 강아지"
1391    1391      연예                              최훈재,"나도 찰칵"
1392    1392      연예                              백서빈,"깔끔 청년"
1393    1393      연예                             구상범 감독,"볼하트"

[1394 rows x 3 columns]

In [29]:
# 4 - 3) 선택/미선택 카테고리 기사 리스트 데이터프레임화
sel_res = dict(sorted(sel_cate_recommend.items(), key=lambda x : -x[1]))
non_sel_res = dict(sorted(non_sel_cate_recommend.items(), key=lambda x : -x[1]))

# 결과에 제목 띄우기 위해 news 테이블과 join
sel_news_id = pd.DataFrame({"news_id" : sel_res.keys()})
result_sel = pd.merge(sel_news_id, news, on="news_id")
result_sel.head(5)

  news_id cate_id                                  title
0     798   생활/문화                어제보다 추운 아침…낮부터 일시 기온 올라
1     124      정치  ‘김대중 정신’ 꺼낸 인요한, 이재명 앞에서 “정쟁 좀 그만합시다”
2     643   생활/문화   민주노조 일군 여공들 "우리가 "공순이"인 게 얼마나 자랑스럽냐"
3     459      사회     "노트북? 전청조가 보냈다"…남현희, 공범 의혹 조목조목 반박
4     710   생활/문화                                 제주 말고기

In [30]:
# 미선택 카테고리에 대한 추천 결과가 필요하면 아래 코드 주석 해제
# non_sel_news_id = pd.DataFrame({"news_id" : non_sel_res.keys()})
# result_non_sel = pd.merge(non_sel_news_id, news, on="news_id")
# result_non_sel.head(5)

In [31]:
# 4 - 4) 최종 출력
print("" + str(target) + "번 회원님, 다음 기사를 추천합니다.")
print(f'{target}번 회원의 선택 카테고리 : ', target_cate)
result_sel.head(10)  # <-- 필요한 갯수만큼

1번 회원님, 다음 기사를 추천합니다.
1번 회원의 선택 카테고리 :  {'사회', '정치', '생활/문화'}

  news_id cate_id                                      title
0     798   생활/문화                    어제보다 추운 아침…낮부터 일시 기온 올라
1     124      정치      ‘김대중 정신’ 꺼낸 인요한, 이재명 앞에서 “정쟁 좀 그만합시다”
2     643   생활/문화       민주노조 일군 여공들 "우리가 "공순이"인 게 얼마나 자랑스럽냐"
3     459      사회         "노트북? 전청조가 보냈다"…남현희, 공범 의혹 조목조목 반박
4     710   생활/문화                                     제주 말고기
5     703   생활/문화       운동조차 조심스러운 "허리 디스크"…걱정없이 할 수 있는 운동 3
6     764   생활/문화  막힌 뇌혈관, 최상급 MRI로 빠르고 정확히 본다… 뇌졸중 진단·치료 앞장
7     765   생활/문화    "전 세계 주목엔 이유 있다"… 양방향 내시경 척추 수술 배우러 한국행
8     696   생활/문화   방심위, 서울시에 뉴스타파 ‘김만배 녹취록 보도’ 신문법 위반 검토 요청
9     114      정치  “옆방서 20분이나 뒷담화” 이준석이 밝힌 ‘안철수씨 조용히 합시다’ 전말

In [32]:
# 추천 점수 체크
test = dict(sorted(sel_cate_recommend.items(), key=lambda x: -x[1]))
for k,v in test.items():
    print(k, ':', v)

798 : 0.13423121104280486
124 : 0.13423121104280486
643 : 0.13423121104280486
459 : 0.13423121104280486
710 : 0.13423121104280486
703 : 0.13423121104280486
764 : 0.12976870516390632
765 : 0.12976870516390632
696 : 0.12976870516390632
114 : 0.12080808993852436
534 : 0.12080808993852436
578 : 0.12080808993852436
73 : 0.12080808993852436
474 : 0.12080808993852436
5 : 0.12080808993852436
102 : 0.12080808993852436
596 : 0.12080808993852436
405 : 0.12080808993852436
136 : 0.12080808993852436
777 : 0.11697193010475818
793 : 0.11697193010475818
629 : 0.11697193010475818
139 : 0.11090002556177428
485 : 0.11090002556177428
526 : 0.11090002556177428
156 : 0.11090002556177428
409 : 0.11090002556177428
481 : 0.11090002556177428
30 : 0.11090002556177428
18 : 0.11090002556177428
54 : 0.11090002556177428
494 : 0.11090002556177428
109 : 0.11090002556177428
454 : 0.11090002556177428
584 : 0.11090002556177428
558 : 0.11090002556177428
68 : 0.11090002556177428
71 : 0.11090002556177428
458 : 0.11090002556177428
492 : 0.11090002556177428
506 : 0.11090002556177428
188 : 0.11090002556177428
419 : 0.11090002556177428
99 : 0.11090002556177428
439 : 0.11090002556177428
486 : 0.11090002556177428
530 : 0.11090002556177428
535 : 0.11090002556177428
184 : 0.11090002556177428
511 : 0.11090002556177428
163 : 0.11090002556177428
575 : 0.11090002556177428
498 : 0.11090002556177428
728 : 0.10884605597934371
663 : 0.10593907444505044
585 : 0.10593907444505044
539 : 0.10593907444505044
579 : 0.10593907444505044
619 : 0.10593907444505044
639 : 0.10593907444505044
743 : 0.10593907444505044
638 : 0.10593907444505044
473 : 0.10593907444505044
555 : 0.10593907444505044
495 : 0.10593907444505044
709 : 0.10593907444505044
423 : 0.10593907444505044
758 : 0.10593907444505044
505 : 0.10593907444505044
477 : 0.10593907444505044
750 : 0.10593907444505044
772 : 0.10593907444505044
551 : 0.10593907444505044
580 : 0.10593907444505044
739 : 0.10593907444505044
618 : 0.10593907444505044
655 : 0.10593907444505044
694 : 0.10593907444505044
732 : 0.10593907444505044
781 : 0.10593907444505044
759 : 0.10593907444505044
457 : 0.10593907444505044
416 : 0.10593907444505044
448 : 0.1046310494895123
588 : 0.1046310494895123
746 : 0.1046310494895123
144 : 0.1046310494895123
631 : 0.09657239582865691
747 : 0.09657239582865691
753 : 0.09657239582865691
632 : 0.09657239582865691
671 : 0.09657239582865691
752 : 0.09657239582865691
653 : 0.09657239582865691
119 : 0.09097816785925636
606 : 0.09097816785925636
603 : 0.09041483013408165
682 : 0.09041483013408165
769 : 0.09041483013408165
712 : 0.09041483013408165
620 : 0.09041483013408165
794 : 0.09041483013408165
656 : 0.09041483013408165
51 : 0.08878560065057219
691 : 0.08724138544978104
92 : 0.08724138544978104
768 : 0.08674427949190669
662 : 0.08585457105482136
608 : 0.08585457105482136
724 : 0.08585457105482136
757 : 0.08585457105482136
429 : 0.083967426956286
145 : 0.083967426956286
147 : 0.083967426956286
153 : 0.083967426956286
552 : 0.083967426956286
175 : 0.083967426956286
96 : 0.083967426956286
500 : 0.083967426956286
622 : 0.07948588753990432
677 : 0.07749842582921285
762 : 0.07749842582921285
730 : 0.07749842582921285
621 : 0.07749842582921285
600 : 0.07698687947429833
146 : 0.07632031385908294
183 : 0.07632031385908294
155 : 0.07632031385908294
708 : 0.07632031385908294
37 : 0.07632031385908294
624 : 0.07632031385908294
192 : 0.07632031385908294
101 : 0.07632031385908294
701 : 0.07632031385908294
773 : 0.07632031385908294
745 : 0.07632031385908294
779 : 0.07632031385908294
651 : 0.07632031385908294
6 : 0.07632031385908294
44 : 0.07632031385908294
540 : 0.0723259116022882
197 : 0.0723259116022882
518 : 0.0723259116022882
88 : 0.0723259116022882
164 : 0.0723259116022882
128 : 0.07048548430432512
170 : 0.07048548430432512
471 : 0.07048548430432512
689 : 0.06947125179709104
755 : 0.06947125179709104
756 : 0.06947125179709104
406 : 0.06947125179709104
462 : 0.06947125179709104
503 : 0.06947125179709104
670 : 0.06947125179709104
589 : 0.06947125179709104
417 : 0.06947125179709104
507 : 0.06947125179709104
561 : 0.06947125179709104
565 : 0.06947125179709104
428 : 0.06947125179709104
444 : 0.06947125179709104
571 : 0.06947125179709104
736 : 0.06947125179709104
740 : 0.06947125179709104
617 : 0.06947125179709104
609 : 0.06947125179709104
491 : 0.06947125179709104
749 : 0.06947125179709104
556 : 0.06947125179709104
785 : 0.06947125179709104
562 : 0.06947125179709104
470 : 0.06947125179709104
604 : 0.06947125179709104
168 : 0.06802878498708982
180 : 0.06581226581158203
707 : 0.06581226581158203
782 : 0.06581226581158203
134 : 0.06581226581158203
680 : 0.06581226581158203
687 : 0.06581226581158203
722 : 0.06581226581158203
151 : 0.06581226581158203
693 : 0.06581226581158203
174 : 0.06581226581158203
612 : 0.06581226581158203
641 : 0.06581226581158203
13 : 0.06581226581158203
780 : 0.06581226581158203
169 : 0.06581226581158203
690 : 0.06581226581158203
172 : 0.06498440561375454
58 : 0.06498440561375454
113 : 0.06498440561375454
117 : 0.06498440561375454
673 : 0.06498440561375454
137 : 0.06498440561375454
69 : 0.06498440561375454
664 : 0.06498440561375454
711 : 0.06498440561375454
154 : 0.06498440561375454
171 : 0.06498440561375454
21 : 0.06498440561375454
634 : 0.06498440561375454
795 : 0.06498440561375454
783 : 0.06498440561375454
120 : 0.06498440561375454
160 : 0.06498440561375454
751 : 0.06498440561375454
599 : 0.06498440561375454
614 : 0.06498440561375454
55 : 0.06498440561375454
688 : 0.06498440561375454
683 : 0.06498440561375454
654 : 0.0637991802113209
741 : 0.0637991802113209
47 : 0.05905385953574926
115 : 0.05905385953574926
430 : 0.05905385953574926
187 : 0.05905385953574926
645 : 0.059015797102187614
726 : 0.059015797102187614
775 : 0.059015797102187614
700 : 0.059015797102187614
770 : 0.059015797102187614
649 : 0.059015797102187614
613 : 0.059015797102187614
611 : 0.059015797102187614
669 : 0.059015797102187614
684 : 0.059015797102187614
70 : 0.05723638070321424
24 : 0.054799662435119106
443 : 0.054799662435119106
84 : 0.054799662435119106
514 : 0.054799662435119106
420 : 0.04579218831544976
536 : 0.04579218831544976
412 : 0.04579218831544976
796 : 0.04579218831544976
665 : 0.04579218831544976
647 : 0.04579218831544976
733 : 0.04579218831544976
635 : 0.04579218831544976
554 : 0.04540246047645019
15 : 0.04540246047645019
484 : 0.04540246047645019
46 : 0.04540246047645019
123 : 0.04540246047645019
121 : 0.04540246047645019
557 : 0.04540246047645019
587 : 0.04540246047645019
189 : 0.04540246047645019
738 : 0.042605728299194706
125 : 0.042605728299194706
142 : 0.042605728299194706
9 : 0.042605728299194706
111 : 0.042605728299194706
686 : 0.042605728299194706
718 : 0.042605728299194706
734 : 0.042605728299194706
697 : 0.042605728299194706
713 : 0.042605728299194706
630 : 0.042605728299194706
698 : 0.042605728299194706
107 : 0.042605728299194706
85 : 0.042605728299194706
610 : 0.042605728299194706
652 : 0.042605728299194706
760 : 0.042605728299194706
16 : 0.042605728299194706
25 : 0.042605728299194706
77 : 0.042605728299194706
623 : 0.042605728299194706
633 : 0.042605728299194706
715 : 0.042605728299194706
681 : 0.042605728299194706
193 : 0.042605728299194706
674 : 0.042605728299194706
716 : 0.042605728299194706
605 : 0.042605728299194706
761 : 0.042605728299194706
672 : 0.042605728299194706
143 : 0.042605728299194706
26 : 0.042605728299194706
0 : 0.042605728299194706
64 : 0.042605728299194706
699 : 0.042605728299194706
87 : 0.042605728299194706
40 : 0.041983713478143
126 : 0.04109974682633933
133 : 0.04109974682633933
176 : 0.04109974682633933
38 : 0.04109974682633933
476 : 0.04109974682633933
510 : 0.04109974682633933
567 : 0.04109974682633933
150 : 0.04109974682633933
191 : 0.04109974682633933
8 : 0.04109974682633933
451 : 0.04109974682633933
53 : 0.04109974682633933
447 : 0.04109974682633933
131 : 0.04109974682633933
62 : 0.04109974682633933
469 : 0.04109974682633933
185 : 0.04109974682633933
89 : 0.04109974682633933
475 : 0.04109974682633933
574 : 0.04109974682633933
19 : 0.04109974682633933
426 : 0.04109974682633933
410 : 0.04109974682633933
482 : 0.04109974682633933
29 : 0.04109974682633933
566 : 0.04109974682633933
461 : 0.04054054054054054
132 : 0.04054054054054054
407 : 0.04054054054054054
586 : 0.04054054054054054
141 : 0.04054054054054054
149 : 0.04054054054054054
80 : 0.04054054054054054
527 : 0.04054054054054054
79 : 0.04054054054054054
496 : 0.04054054054054054
520 : 0.04054054054054054
173 : 0.04054054054054054
549 : 0.04054054054054054
98 : 0.04054054054054054
488 : 0.04054054054054054
194 : 0.04054054054054054
595 : 0.04054054054054054
41 : 0.04054054054054054
529 : 0.04054054054054054
76 : 0.04000355602969987
425 : 0.04000355602969987
129 : 0.04000355602969987
135 : 0.04000355602969987
563 : 0.04000355602969987
17 : 0.04000355602969987
50 : 0.04000355602969987
83 : 0.04000355602969987
559 : 0.04000355602969987
523 : 0.04000355602969987
10 : 0.04000355602969987
110 : 0.04000355602969987
422 : 0.04000355602969987
81 : 0.04000355602969987
538 : 0.04000355602969987
78 : 0.04000355602969987
116 : 0.04000355602969987
11 : 0.04000355602969987
66 : 0.04000355602969987
467 : 0.04000355602969987
408 : 0.04000355602969987
56 : 0.04000355602969987
431 : 0.04000355602969987
167 : 0.04000355602969987
14 : 0.04000355602969987
63 : 0.03717611978224573
509 : 0.03717611978224573
441 : 0.03717611978224573
130 : 0.03717611978224573
28 : 0.03717611978224573
94 : 0.03717611978224573
479 : 0.03717611978224573
34 : 0.03717611978224573
660 : 0.03717611978224573
766 : 0.03717611978224573
771 : 0.03717611978224573
569 : 0.03717611978224573
181 : 0.03717611978224573
628 : 0.03717611978224573
513 : 0.03717611978224573
2 : 0.031068488300060006
27 : 0.031068488300060006
478 : 0.031068488300060006
460 : 0.031068488300060006
190 : 0.031068488300060006
480 : 0.031068488300060006
165 : 0.031068488300060006
436 : 0.031068488300060006
421 : 0.031068488300060006
570 : 0.031068488300060006
445 : 0.031068488300060006
483 : 0.031068488300060006
86 : 0.031068488300060006
542 : 0.031068488300060006
440 : 0.031068488300060006
521 : 0.031068488300060006
522 : 0.031068488300060006
528 : 0.031068488300060006
572 : 0.031068488300060006
106 : 0.031068488300060006
446 : 0.031068488300060006
463 : 0.031068488300060006
43 : 0.031068488300060006
432 : 0.031068488300060006
568 : 0.031068488300060006
48 : 0.031068488300060006
57 : 0.031068488300060006
140 : 0.031068488300060006
548 : 0.031068488300060006
52 : 0.031068488300060006
725 : 0.030794751789719334
678 : 0.030528125543633176
791 : 0.030528125543633176
401 : 0.030015011259383207
626 : 0.030015011259383207
644 : 0.030015011259383207
449 : 0.029291651677583116
166 : 0.027989142318762
100 : 0.027989142318762
642 : 0.027989142318762
602 : 0.027989142318762
195 : 0.027989142318762
676 : 0.027989142318762
127 : 0.027788500718836418
531 : 0.027592113093901974
90 : 0.027592113093901974
438 : 0.02702702702702703
784 : 0.02507061052819501
702 : 0.02507061052819501
427 : 0.02410863720076273
723 : 0.02410863720076273
636 : 0.01453095484297741
727 : 0.01453095484297741
679 : 0.01453095484297741
453 : 0.01453095484297741
658 : 0.01453095484297741
564 : 0.01453095484297741
489 : 0.01453095484297741
790 : 0.01453095484297741
411 : 0.01453095484297741
706 : 0.01453095484297741
668 : 0.01453095484297741
659 : 0.01453095484297741
720 : 0.01453095484297741
797 : 0.01453095484297741
789 : 0.01453095484297741
424 : 0.01453095484297741
667 : 0.01453095484297741
704 : 0.01453095484297741
592 : 0.01453095484297741
792 : 0.01453095484297741
497 : 0.013699915608779777
637 : 0.013699915608779777
650 : 0.013699915608779777
685 : 0.013699915608779777
742 : 0.013699915608779777
456 : 0.013699915608779777
593 : 0.013699915608779777
403 : 0.013699915608779777
754 : 0.013699915608779777
767 : 0.013699915608779777
524 : 0.013699915608779777
721 : 0.013699915608779777
748 : 0.013699915608779777
661 : 0.013699915608779777
515 : 0.013699915608779777
731 : 0.013699915608779777
499 : 0.013699915608779777
442 : 0.013699915608779777
582 : 0.013699915608779777
65 : 0.012837404149077419
7 : 0.012837404149077419
465 : 0.012837404149077419
532 : 0.012837404149077419
4 : 0.012837404149077419
49 : 0.012837404149077419
61 : 0.012837404149077419
541 : 0.012837404149077419
93 : 0.012837404149077419
553 : 0.012837404149077419
103 : 0.012837404149077419
75 : 0.012837404149077419
404 : 0.012837404149077419
544 : 0.012837404149077419
152 : 0.012837404149077419
547 : 0.012837404149077419
590 : 0.012837404149077419
464 : 0.012837404149077419
591 : 0.012837404149077419
36 : 0.012837404149077419
517 : 0.012683657235796026
695 : 0.012683657235796026
774 : 0.012683657235796026
717 : 0.012683657235796026
763 : 0.012683657235796026
615 : 0.012683657235796026
20 : 0.0
45 : 0.0
67 : 0.0
418 : 0.0
550 : 0.0
573 : 0.0
581 : 0.0
198 : 0.0
97 : 0.0
413 : 0.0
435 : 0.0
468 : 0.0
502 : 0.0
158 : 0.0
35 : 0.0
487 : 0.0
508 : 0.0
525 : 0.0
594 : 0.0
450 : 0.0
543 : 0.0
597 : 0.0
118 : 0.0
414 : 0.0
466 : 0.0
31 : 0.0
33 : 0.0
186 : 0.0
402 : 0.0
455 : 0.0
32 : 0.0
576 : 0.0
1 : 0.0
91 : 0.0
399 : 0.0
546 : 0.0
22 : 0.0
519 : 0.0
179 : 0.0
493 : 0.0
537 : 0.0
138 : 0.0
177 : 0.0
82 : 0.0
437 : 0.0
490 : 0.0
560 : 0.0
512 : 0.0
583 : 0.0
434 : 0.0
105 : 0.0
72 : 0.0
501 : 0.0
74 : 0.0