In [87]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import random
import oracledb
import cx_Oracle

<h2> 선호 카테고리 테이블 DB에 임시 저장</h2>
<p>select * from preference</p>

In [91]:
pref = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\test2_preference.csv", index_col='mem_id', encoding='cp949')
pref

       cate_id
mem_id
1        IT/과학
1           사회
1           경제
2           연예
2           사회
...        ...
249         경제
249      생활/문화
250         사회
250         경제
250      생활/문화

[750 rows x 1 columns]

In [92]:
# 각 회원 별 무작위 선호 카테고리 난수 지정 -> 테스트 회원은 250명으로 임시 설정
arr = []
for i in range(250):
    tmp = random.sample(range(7), 3)
    arr.append(tmp[0])
    arr.append(tmp[1])
    arr.append(tmp[2])

print(arr)

[0, 4, 3, 1, 3, 4, 6, 4, 3, 0, 6, 5, 0, 4, 5, 5, 2, 4, 5, 2, 4, 3, 6, 0, 3, 6, 1, 0, 4, 1, 0, 5, 6, 5, 2, 3, 4, 6, 0, 4, 6, 0, 5, 1, 4, 2, 5, 1, 6, 3, 2, 1, 5, 0, 3, 6, 2, 0, 6, 5, 4, 1, 0, 6, 3, 4, 5, 3, 2, 6, 4, 2, 3, 5, 1, 5, 3, 1, 1, 2, 4, 2, 0, 6, 3, 4, 2, 3, 4, 6, 4, 5, 6, 0, 1, 6, 2, 4, 3, 3, 6, 1, 0, 5, 2, 2, 3, 0, 5, 2, 3, 1, 5, 3, 5, 6, 2, 2, 0, 1, 0, 2, 4, 4, 1, 3, 3, 6, 0, 0, 5, 3, 3, 6, 5, 1, 4, 6, 0, 3, 1, 0, 3, 2, 4, 6, 5, 4, 1, 0, 3, 1, 2, 1, 2, 3, 3, 0, 5, 1, 6, 5, 1, 6, 3, 3, 0, 1, 5, 1, 4, 1, 0, 2, 0, 1, 6, 1, 3, 6, 1, 5, 0, 6, 5, 0, 2, 1, 5, 0, 6, 3, 1, 6, 3, 1, 0, 6, 3, 5, 0, 1, 0, 6, 3, 1, 5, 6, 3, 4, 1, 6, 0, 3, 0, 1, 0, 6, 3, 3, 6, 0, 0, 1, 6, 2, 0, 3, 3, 1, 5, 6, 1, 0, 5, 3, 4, 3, 2, 6, 0, 1, 6, 1, 6, 5, 0, 6, 1, 6, 1, 5, 5, 4, 6, 3, 1, 4, 1, 3, 0, 3, 2, 0, 2, 4, 6, 3, 6, 4, 6, 0, 2, 6, 3, 5, 2, 0, 6, 1, 6, 3, 4, 0, 1, 1, 0, 5, 1, 0, 4, 3, 1, 5, 3, 0, 1, 5, 1, 4, 3, 5, 0, 4, 3, 6, 1, 5, 0, 0, 6, 2, 0, 3, 5, 1, 3, 2, 2, 6, 0, 1, 2, 4, 3, 1, 2, 5, 1, 3, 4, 3, 2, 2, 1, 5, 0, 2, 1, 0, 5, 1, 6, 3, 0, 4, 5, 1, 2, 5, 6, 6, 0, 2, 3, 1, 2, 6, 1, 5, 6, 3, 5, 3, 1, 6, 1, 5, 4, 3, 6, 1, 6, 1, 4, 5, 3, 0, 6, 0, 2, 3, 2, 6, 6, 4, 1, 6, 5, 3, 3, 2, 4, 6, 5, 4, 5, 0, 3, 2, 6, 4, 5, 2, 4, 3, 4, 1, 1, 5, 4, 6, 0, 1, 0, 2, 5, 6, 5, 1, 2, 6, 0, 0, 4, 5, 1, 6, 0, 2, 1, 5, 0, 1, 3, 5, 4, 0, 6, 2, 1, 6, 2, 5, 0, 3, 2, 1, 3, 6, 0, 2, 4, 5, 6, 1, 6, 5, 3, 2, 1, 4, 6, 3, 4, 2, 3, 5, 6, 2, 5, 6, 0, 4, 6, 4, 5, 4, 2, 5, 4, 5, 1, 3, 5, 4, 2, 1, 0, 1, 4, 5, 6, 0, 4, 5, 6, 1, 0, 3, 1, 0, 5, 3, 6, 3, 2, 1, 3, 2, 5, 3, 4, 5, 3, 1, 4, 2, 1, 4, 2, 1, 5, 3, 2, 3, 4, 1, 2, 0, 4, 6, 3, 2, 5, 3, 6, 2, 1, 0, 1, 5, 6, 0, 2, 5, 4, 3, 5, 1, 6, 4, 6, 1, 4, 0, 2, 4, 5, 0, 2, 6, 1, 5, 3, 2, 4, 6, 3, 1, 4, 5, 6, 3, 2, 6, 4, 6, 1, 4, 1, 0, 5, 6, 4, 1, 4, 6, 5, 6, 1, 4, 6, 3, 2, 0, 4, 5, 3, 0, 5, 6, 1, 4, 2, 5, 4, 6, 5, 1, 3, 4, 4, 5, 0, 5, 0, 4, 5, 1, 4, 3, 0, 6, 3, 6, 1, 5, 4, 6, 5, 1, 3, 4, 2, 6, 1, 4, 3, 0, 1, 3, 6, 0, 1, 6, 4, 0, 6, 0, 2, 6, 1, 4, 3, 2, 5, 5, 4, 0, 3, 1, 6, 6, 4, 5, 3, 4, 0, 3, 6, 5, 6, 0, 4, 4, 0, 3, 6, 3, 4, 4, 5, 6, 4, 5, 6, 2, 6, 0, 5, 0, 1, 0, 4, 3, 6, 3, 1, 0, 4, 6, 4, 0, 1, 6, 5, 0, 4, 1, 5, 0, 3, 5, 3, 5, 4, 1, 2, 0, 3, 0, 4, 1, 6, 3, 6, 0, 1, 5, 0, 6, 2, 4, 3, 2, 1, 0, 6, 3, 4, 2, 1, 4, 1, 0, 4, 0, 3, 1]

In [93]:
# arr에 배정된 숫자에 따라 cate에서 인덱스로 카테고리 지정
cate = ['정치', '연예', '경제', '사회', '생활/문화', '세계', 'IT/과학']
pref['cate_id'] = [cate[a] for a in arr]
pref

       cate_id
mem_id
1           정치
1        생활/문화
1           사회
2           연예
2           사회
...        ...
249         정치
249      생활/문화
250         정치
250         사회
250         연예

[750 rows x 1 columns]

In [94]:
pref.to_csv("C:\\Users\\PC\\Desktop\\library_test\\test2_preference.csv", encoding='cp949')
# 파일로 생성하는 코드

<h2>각 회원의 조회 기사를 각 회원의 카테고리 내에서 선택해서 배정</h2>
<p>select * from user_log(?)</p>

In [95]:
news = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\test2_news.csv", index_col='news_id', encoding='cp949')
news
# 기사 제목, 아이디, 카테고리만 가져옴

        cate_id                                  title
news_id
0            정치     이탈리아 지지표 흡수는 기본… 중립 성향 표심 잡는 게 관건
1            정치  이준석 “영남 정치인들 편하게 놔두지 않겠다”…영남 신당 추진 시사
2            정치   주호영 “서울 갈 일 없다”…이준석 “대구에서 어려운 승부할 것”
3            정치   28억 재산 누락' 김대기 "단순 실수"…야당 "대국민 사과해야"
4            정치       與 핵심, '거취 압박' 대응 자제...내부선 불만 기류도
...         ...                                    ...
1389         연예                            김영,'훈훈한 미소'
1390         연예                          신연서,'소중한 강아지'
1391         연예                            최훈재,'나도 찰칵'
1392         연예                            백서빈,'깔끔 청년'
1393         연예                           구상범 감독,'볼하트'

[1394 rows x 2 columns]

In [97]:
# 250명이 자신의 카테고리에 소속된 기사 중 몇개를 무작위로 고르는 로그 16000개
data2 = {'mem_id' : [], 'news_id' : []}

while len(data2['mem_id']) < 16000:  # 로그가 16000개가 쌓일때까지 반복
    mem_id = np.random.randint(1,251)  # mem_id 랜덤 생성
    news_id = np.random.randint(0, 1394) # news_id 랜덤 생성

    sel_cate = pref[pref.index == mem_id]['cate_id'].values # mem_id 유저가 선택한 카테고리

    if news.loc[news_id, 'cate_id'] in sel_cate:
        data2['mem_id'].append(mem_id)
        data2['news_id'].append(news_id)

log2 = pd.DataFrame(data2)
log2

       mem_id  news_id
0         185      796
1         190     1239
2          63     1382
3         174     1214
4         175      477
...       ...      ...
15995     143     1144
15996     179     1175
15997     239      938
15998     125     1206
15999     142      192

[16000 rows x 2 columns]

In [116]:
# 제대로 동작하는지 확인
user = 2  # 유저 번호 입력
article = 938 # 기사 번호 입력

print("입력한 유저가 고른 카테고리")
print(pref[pref.index == user].values)
print("==============================")

print("입력한 기사번호 소속 카테고리 및 제목")
print(news[news.index == article])

입력한 유저가 고른 카테고리
[[1 '사회']]
==============================
입력한 기사번호 소속 카테고리 및 제목
        cate_id                          title
news_id
938          세계  “팔레스타인 가자지구가 어린이들의 무덤이 되고 있다”

In [106]:
log2_2 = pd.merge(log2, news, on='news_id') # 카테고리와 제목 가져오기
log2_2.to_csv("C:\\Users\\PC\\Desktop\\library_test\\test4_log2.csv", encoding='cp949')

여기서부터 DB 연결

In [107]:
log2_2

       mem_id  news_id cate_id                                     title
0         185      796   생활/문화              겨울 시작 '입동' 추위…주말에는 더 강한 찬 바람
1          57      796   생활/문화              겨울 시작 '입동' 추위…주말에는 더 강한 찬 바람
2         247      796   생활/문화              겨울 시작 '입동' 추위…주말에는 더 강한 찬 바람
3           6      796   생활/문화              겨울 시작 '입동' 추위…주말에는 더 강한 찬 바람
4          57      796   생활/문화              겨울 시작 '입동' 추위…주말에는 더 강한 찬 바람
...       ...      ...     ...                                       ...
15995      12      209      경제     20억 빌라 소유' 유해진, 성북동 150평 주택 샀다…45억 현찰
15996      63      209      경제     20억 빌라 소유' 유해진, 성북동 150평 주택 샀다…45억 현찰
15997     113      209      경제     20억 빌라 소유' 유해진, 성북동 150평 주택 샀다…45억 현찰
15998      34     1129   IT/과학  ‘통합’다나와·에누리 어떨까?…커넥트웨이브“AI로 고객 문제해결”(종합)
15999     106      345      경제                    서울편입' 힘 못썼네 … 김포 청약 참패

[16000 rows x 4 columns]

In [108]:
# DB 접속
con = cx_Oracle.connect(user="ist", password='ist', dsn='localhost:1521/xe')
cursor = con.cursor()

In [117]:
# 임의 난수 로그 insert
for i in range(16000):
    mid, nid, cid = log2_2.loc[i][:3]
    sql = "INSERT INTO user_log(log_id, mem_id, cate_id, news_id) VALUES (log_seq.NEXTVAL, '" + str(mid) + "', '" + str(cid) + "', '" + str(nid) +"')"
    cursor.execute(sql)
    con.commit()

In [110]:
pref = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\test2_preference.csv", encoding='cp949')
pref

     mem_id cate_id
0         1      정치
1         1   생활/문화
2         1      사회
3         2      연예
4         2      사회
..      ...     ...
745     249      정치
746     249   생활/문화
747     250      정치
748     250      사회
749     250      연예

[750 rows x 2 columns]

In [111]:
# 유저별 선택한 카테고리 insert
for i in range(750):
    mid, cid = pref.loc[i][:2]
    sql = "INSERT INTO test_pref(cate_id, mem_id) VALUES ('" + str(cid) + "', '" + str(mid) + "')"
    cursor.execute(sql)
    con.commit()

In [119]:
# 뉴스 DB에 삽입
news = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\test2_news.csv", encoding='cp949')
news

      news_id cate_id                                  title
0           0      정치     이탈리아 지지표 흡수는 기본… 중립 성향 표심 잡는 게 관건
1           1      정치  이준석 “영남 정치인들 편하게 놔두지 않겠다”…영남 신당 추진 시사
2           2      정치   주호영 “서울 갈 일 없다”…이준석 “대구에서 어려운 승부할 것”
3           3      정치   28억 재산 누락' 김대기 "단순 실수"…야당 "대국민 사과해야"
4           4      정치       與 핵심, '거취 압박' 대응 자제...내부선 불만 기류도
...       ...     ...                                    ...
1389     1389      연예                            김영,'훈훈한 미소'
1390     1390      연예                          신연서,'소중한 강아지'
1391     1391      연예                            최훈재,'나도 찰칵'
1392     1392      연예                            백서빈,'깔끔 청년'
1393     1393      연예                           구상범 감독,'볼하트'

[1394 rows x 3 columns]

In [129]:
for i in range(1394):
    nid, cid, tt = news.loc[i]
    tt = tt.replace("'", '"')
    sql = "INSERT INTO test_news(news_id, cate_id, title) VALUES ('" + str(nid) + "', '" + str(cid) + "', '" + tt + "')"
    print(sql)
    cursor.execute(sql)
    con.commit()

INSERT INTO test_news(news_id, cate_id, title) VALUES ('0', '정치', '이탈리아 지지표 흡수는 기본… 중립 성향 표심 잡는 게 관건 ')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('1', '정치', '이준석 “영남 정치인들 편하게 놔두지 않겠다”…영남 신당 추진 시사')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('2', '정치', '주호영 “서울 갈 일 없다”…이준석 “대구에서 어려운 승부할 것”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('3', '정치', '28억 재산 누락" 김대기 "단순 실수"…야당 "대국민 사과해야"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('4', '정치', '與 핵심, "거취 압박" 대응 자제...내부선 불만 기류도')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('5', '정치', '"왜 "안철수씨"라고 했냐면"…이준석 "복국집 고함" 입 열었다')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('6', '정치', ' 한동훈 "마약으로 어떻게 국면을 전환하겠다는 것인지 오히려 묻고 싶다"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('7', '정치', '민주당 내부 "도덕성 회복해야" "이재명부터 험지로" 목소리 나와')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('8', '정치', '홍준표 “듣보잡이 설친다” / 친명 “총선 위기감” / 신원식, 주식 했다 혼쭐')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('9', '정치', '‘이준석 신당’ 부산 파급력…與 “후폭풍 클것” 野 “영향 미미”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('10', '정치', '이준석 "창당하면 가장 어려운 역할... 그게 대구 공략일 것"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('11', '정치', '인요한 "이준석에 통크게 제안…돌아와 총선 중책 맡아달라"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('12', '정치', ' 尹, "3년" 짜리 조희대 대법원장 후보 지명')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('13', '정치', ' 김성태 “이재명 인재위원장? 이재명에게 악수, 국민의힘은 ‘땡큐’”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('14', '정치', ' 엄경영 "김종인 전 비대위원장이 이준석 전 대표를 일회용으로 써먹으려 해"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('15', '정치', '여론조사 ‘폴A’ 돌려보니…사람이냐 ARS냐 따라 7%p 차이')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('16', '정치', '고민정 "한동훈, 탄핵 하려면 하라고? 착각에 빠진 관종"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('17', '정치', ' 홍준표의 대통령 칭찬 / "개 식용 금지법" 통과? / 국방위 파행')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('18', '정치', '대구MBC 보도 무혐의에도 대구시 "잘못된 수사" 이의신청')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('19', '정치', '유정복 만난 이재명 "교통난부터" 김포 편입 사실상 반대')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('20', '정치', '김병민 "이재명 인재위원장?..어차피 이판사판, "李 결사보위당" 배수진 완성"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('21', '정치', '洪 쓴소리 듣고, DJ 띄우며…인요한, 이재명 향해 “정쟁 그만”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('22', '정치', ' 국힘 “광주전남도 메가시티”…협의는 없었다')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('23', '정치', '홍준표 "대통령 믿고 설치는 듣보잡들 때문 당 개판"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('24', '정치', '인요한 조부모" 학교 나온 조수진 "린튼家 한국 사랑은 대단"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('25', '정치', '또 인사개입 논란…김규현 국정원장 교체 검토')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('26', '정치', '서울시 김포구" 최초 제안한 홍철호 "총선용 정치쇼? 김포주민들 매일이 지옥철...')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('27', '정치', '민주 “이동관 탄핵안 거의 공감대”…내일 본회의 직전 의총서 결정')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('28', '정치', '홍준표 “망가진 당 혁신 어려워”…인요한 “어렵지만 해야할 일”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('29', '정치', '주호영 "서울 안 간다…대구서 정치 시작했으니 대구서 마쳐야"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('30', '정치', '"보복은 못 쓰는 것이여"…인요한 "DJ 성대모사" 웃음 터졌다')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('31', '정치', '박정현 민주당 최고위원 “친명-비명은 프레임일 뿐…충청권 목소리 대변할 것”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('32', '정치', '野, 노란봉투법·방송법 강행처리 시동…‘이동관 탄핵’도 군불')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('33', '정치', '"내년 총선에 불출마 하나?"…소속 의원 전원에 공문 보낸 민주')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('34', '정치', '민주당 인재위원장 맡은 이재명… ‘친명 공천’ 현실화하나')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('35', '정치', '홍준표 만난 인요한 “도와달라”… 홍 “尹 믿고 ‘듣보잡’들 설쳐”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('36', '정치', '금태섭 “이준석 만날 것”… "신당 초대장"에 호응')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('37', '정치', '對與 파상공세에 얼어붙은 정국… 與 ‘필리버스터’로 대치 ')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('38', '정치', '‘쌍특검’ 처리도 벼르는 野… 다시 정쟁 속으로 ')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('39', '정치', '대통령실 "비서실장 재산신고 누락 징계처분 공개 어렵다"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('40', '정치', '尹, 한·이탈리아 정상회담…"미래지향적 협력 강화" ')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('41', '정치', '서울 편입론에 김포 현역 등판... "그래서 찬성?반대?"vs"서울시 부산구"까지 갈 듯"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('42', '정치', '대법원장 후보자에 조희대 前 대법관')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('43', '정치', '이재명 “조금씩 확장하다 보면 제주도 빼고 다 서울 되나"…국토 불균형 해소 주장')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('44', '정치', '김건희 여사, 국립소록도병원 방문…한센인 환자 위로 ')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('45', '정치', '민주로 옮겨붙은 ‘험지 출마론’… 비명계, 친명 압박')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('46', '정치', '영남권서 활발한 행보… ‘이준석 신당’은 PK당?')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('47', '정치', '홍준표, 인요한 만나 親尹에 “듣보잡”…주호영은 험지출마 공개거부')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('48', '정치', '文정부 땐 논의조차 안하더니…巨野 "총선 볼모"된 파업조장법')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('49', '정치', '주호영 "서울 안 간다…대구서 정치 시작했으면 대구서 마치는 것"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('50', '정치', ' 이준석 “영남에서 승부를 봐야”…‘영남 신당’ 추진 뜻')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('51', '정치', '김근식 “이준석, 이 정도면 인성에 심각한 문제…세상은 다 자기 아래”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('52', '정치', ' "이준석에 신당 창당 조언"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('53', '정치', '인요한의 힘겨운 "비윤계 구애"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('54', '정치', '"홍준표 `듣보잡` 비난은 애정…尹 이준석에 다리 놔줄 것" 당내 반응')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('55', '정치', '추미애 "민주당, 이재명 "선거개혁" 공약 부활시켜야"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('56', '정치', '‘인기 없어도 한다’던 정부·여당, 정책도 혁신도 ‘표퓰리즘’만')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('57', '정치', '윤 대통령, 조희대 대법원장 후보 지명…이균용 낙마 뒤 33일만')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('58', '정치', '이준석이 밝힌 복국집 고함 내막은…"안철수, 제발 밥 좀 조용히 먹자"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('59', '정치', '印 만난 洪 “대통령 호가호위 세력 정리해야”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('60', '정치', '류호정 “이준석 함께? 오히려 좋아”…선그은 비명계, ‘설화’ 빚는 이준석')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('61', '정치', '尹, 새 대법원장에 ‘미스터 소수 의견’ 조희대 전 대법관 지명')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('62', '정치', '운명의 장난?…"안철수씨 조용히 좀!" 여의도 복집에서 무슨 일이')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('63', '정치', '무리수 연발하는 이준석 전 국민의힘 대표, 신당 창당은커녕 고사 위기 우려 나와')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('64', '정치', '김대기 비서실장 "28억" 재산신고 누락에… 민주 "합당한 처벌받아야"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('65', '정치', ' 인요한 "좀 도와달라" 홍준표 ""듣보잡"이 설쳐 당이 개판···싫다"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('66', '정치', '식당서 고함친 이준석에…"신당 성공 어려운 이유", "싸가지 정치"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('67', '정치', ' - 18:00')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('68', '정치', '김기현보단 인요한?…"사실상 여당 대표 역할 수행 중"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('69', '정치', '“김포시 서울 편입돼도 군사작전상 안보 큰 지장 없어”…메가서울 힘 싣는 신원식')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('70', '정치', '인요한, 이재명에 "이제 정쟁 좀 그만"... 참석자 일부 항의')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('71', '정치', '“I am 정의” 조국 총선 출마 가시권…"호남 신당설"도 나왔다')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('72', '정치', '홍준표 "尹과 아직 신뢰관계 있어, 주변 듣보잡들이 문제"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('73', '정치', '한동훈 "마약 범람, 분위기 탄다… 공인들 혐의 밝혀지면 엄벌해야"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('74', '정치', '인요한, 전라도 사투리로 DJ 성대모사…"보복은 못 쓰는 것이여"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('75', '정치', '민주당 비명계 의원들 탈당 가능성 잇따라 시사.."불공정 공천이 방아쇠"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('76', '정치', '행안장관, 빈대 발생지 공개 요구에 “감춘다고 해결될 일 아냐”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('77', '정치', '"도와달라" 인요한 요청에…홍준표 "난 듣보잡들 때문에 싫어"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('78', '정치', '인요한, 전라도 사투리로 DJ 성대모사…"보복은 못 쓰는 것이여"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('79', '정치', '막말·설화 논란 이충상 인권위원의 궤변 "저 인권감수성 있다"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('80', '정치', '총선 ‘험지 출마’ 요구받는 이재명···당 인재위원장 맡기로')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('81', '정치', '용산·각료 출마 러시, 텃밭에 집중…달아오른 與 공천경쟁(종합)')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('82', '정치', '“삐라 살포에 불소나기”…북한, 김정은 ‘출생비밀’ 유포 두렵나')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('83', '정치', '민주당, 이동관·검사 탄핵 드라이브…"탄핵 안하면 나라 망친다"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('84', '정치', '이재명 "DJ 존경과 그리운 마음 커져" 인요한 "경제위기 슬기롭게 넘겨주신 분" ')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('85', '정치', '홍준표 "대통령 이용하는 사람들이 국가 농단…정리 해달라"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('86', '정치', '"딱 이정도 톤이었어요 안철수 씨~" "식당 고성" 이준석이 밝힌 전말')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('87', '정치', '공수처장 바꿔야하는데…野비토권 없앤 민주당, 제 발등 찍었다')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('88', '정치', '이재명으로 옮겨 붙은 ‘험지 출마론’…친명계 “일고 가치도 없어”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('89', '정치', '공천권 쥔 채 인재영입 직접 나선 李… 비명 "사당화하나"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('90', '정치', ' 인요한 만난 홍준표 "이준석 신당 만들면 김기현은 먹잇감 돼"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('91', '정치', '與 단체장들, "메가서울" 시각차…"정치 쇼", "지방 메가시티 조성 먼저"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('92', '정치', '민주당 정국 주도권 잡기 반격…3국조·개식용 종식법  등 당론 채택, 이동관·검사 4명 탄핵도 만지작')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('93', '정치', '대북전단살포금지법" 위헌 결정 빌미..한반도 안보 긴장 수위 높이는 北')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('94', '정치', 'DJ 성대모사 한 인요한, 이재명 향해 “정쟁 좀 그만합시다”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('95', '정치', '대통령실, 김대기 비서실장 재산신고 누락 논란에 “단순한 실수”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('96', '정치', '장예찬, 안철수에 고함친 이준석에 "인성의 문제"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('97', '정치', '北, 대북전단 금지법 위헌 결정 맹비난 "대한민국 종말 기폭제"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('98', '정치', '예산·의사일정 놓고 국방위에서 "별"들의 설전')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('99', '정치', '홍준표 “尹 호가호위 세력 정리해야”…인요한 “명심할 것”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('100', '정치', '""듣보잡" 설쳐 당 개판" 홍준표, 인요한에 쓴소리…더 커지는 與혁신 압박')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('101', '정치', '보수색 강한 "Mr. 소수의견"… 野, 또 낙마 시키기엔 여론부담')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('102', '정치', '김종인·홍준표도 "불출마 압박"…김기현 "결단" 주목')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('103', '정치', '인요한, 이재명 향해 "대표님, 이제 정쟁 좀 그만 합시다"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('104', '정치', '인요한 "보복은 못 쓰는 것이여" DJ성대모사…이재명 면전서 "정쟁 그만하자"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('105', '정치', '‘청년’ ‘호남’ 내건 국민의힘, ‘이준석 키워드’만 좇는다')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('106', '정치', '진중권 "인요한에 영어 쓴 이준석, 잘못한 것 맞다…타자화 부적절"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('107', '정치', '민주당, KBS·MBC·YTN "방송장악" 국정조사요구서 제출')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('108', '정치', '46조 투자 "걸림돌" 싹 치워준다 … 하남 "더 스피어" 2025년 첫삽')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('109', '정치', '"안보 지장없다"…메가서울 힘 실어주는 신원식')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('110', '정치', '대통령실, "김대기 재산신고 누락"에 "징계대상 아냐…단순 실수"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('111', '정치', '한 발 뺀 민주당 "한동훈 탄핵 논의 안 해"…이동관은 논의 지속')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('112', '정치', '"메가서울, 세계적 추세" "북 박격포 사거리"…예결위 충돌(종합)')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('113', '정치', ' 윤 대통령, 11~12월 미국·영국·프랑스·네덜란드 4개국 순방 등')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('114', '정치', '“옆방서 20분이나 뒷담화” 이준석이 밝힌 ‘안철수씨 조용히 합시다’ 전말')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('115', '정치', '巨野, 이슈선점 밀리자 …"불로소득 대기업에 횡재세 더 매기자"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('116', '정치', '인요한, 이재명 면전서 "정쟁 좀 그만합시다!"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('117', '정치', '대통령실, 김대기 재산신고 누락에 "단순 실수…징계대상 아냐"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('118', '정치', '민주당, ‘현역의원 페널티 강화’로 공천룰 검토… 당내 새 갈등 뇌관')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('119', '정치', '인요한, 대구서 홍준표 면담‥청년 간담회도')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('120', '정치', '김건희 여사 "소록도, 환자만의 공간 아냐…편견 없애려 왔어"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('121', '정치', '민주당 단톡방에 올라온 장문의 글…“강서 승리 후 방심하고 있다”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('122', '정치', '인요한, 이재명 향해 “DJ 마지막 유언은 ‘사랑’…정쟁 좀 그만하자”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('123', '정치', '찰스3세가 부른 첫 손님 尹…두 정상 함께 마차행진·근위대 사열')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('124', '정치', '‘김대중 정신’ 꺼낸 인요한, 이재명 앞에서 “정쟁 좀 그만합시다”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('125', '정치', '“김포 다음은 공매도” 여당발 ‘깜짝’ 정책···시민들 “민생이 장난이냐”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('126', '정치', ' "신원식 장관, 국방에도 바쁘실 텐데 다방면으로 바쁘신 것 같아요"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('127', '정치', '인요한 “이대남 불쌍해…시험 치면 여자들이 많이 돼”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('128', '정치', '민주 "이동관 탄핵안 내일 결론"…한동훈 쏙 빠졌다')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('129', '정치', '탄핵 논의에 한동훈 발끈 "내가 위증교사라도 했나?", 與 "탄핵중독당"外')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('130', '정치', '野 신현영 "탄핵 대상 너무 많아 저희도 헷갈려"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('131', '정치', '인요한 "이재명, 정쟁 그만하자…생각 달라도 미워하지 않아야"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('132', '정치', '“돈 많이 벌었으니 내라”…여야 다 꺼내든 이 세금, 어찌하오리까  ')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('133', '정치', ' "선거제 개편" 핵심은?…이탄희 의원에게 듣는다')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('134', '정치', '특활비 벼르는 민주당, 또 "수사 막는 것" 한동훈 반발')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('135', '정치', 'KF-21 전투기 1차 생산 20대…조건부로 20대 추가 추진')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('136', '정치', '野, 9일 "노란봉투법" 강행처리 시도…與, 필리버스터·거부권 맞불')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('137', '정치', ' 홍준표 "듣보잡" 발언…이준석·안철수는 "칸막이" 신경전')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('138', '정치', '北 "삐라 살포는 선제공격"…김정은 "확성기 포비아" 드러냈나')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('139', '정치', '고민정, ‘탄핵 하려면 하라’ 한동훈에 “관종, 자신만 보고 있단 착각”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('140', '정치', '대법원장 후보에 조희대 전 대법관…"사법신뢰 회복 적임자"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('141', '정치', '‘이준석 신당론’에 갑론을박…금태섭 “조만간 만날 것” 인요한 “돌아와 중책 맡아주길”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('142', '정치', '與 혁신위원장이 野 대표에 말했다···“정쟁 그만합시다”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('143', '정치', ' 이언주 “신당, 정치·보수 혁신 있다면 열려있어”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('144', '정치', '野 "검경·국정원 특활비 대폭삭감"…與 "사정기관 손발묶기"(종합)')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('145', '정치', ' 민주, 이동관 탄핵안 내일 의총서 결정… 한동훈 탄핵안 안건 못 올라')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('146', '정치', '대통령실 "김대기 실장 재산신고 누락 처분, 공개 어려워"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('147', '정치', '이준석 ‘식당 고함’에 장예찬 “인성의 문제”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('148', '정치', '“北 따라오지 마!”…北과 격차 벌일 정찰위성 등 우주력 건설에 승부수')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('149', '정치', '인요한 "이재명 대표님, 정쟁 좀 그만합시다…나라위해 같이 하자"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('150', '정치', '인요한 "여당 혁신 도와달라"… 홍준표 "듣보잡 때문에 싫다"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('151', '정치', '총선기획단 띄운 국힘, "친윤" 전략공천 질문엔 답 피해')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('152', '정치', '비명계 "이재명 험지 출마해야...이준석 신당은 함께 못해"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('153', '정치', '김대기 재산누락 논란…대통령실 “선출직·정무직은 징계 대상 아냐”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('154', '정치', '“안철수 20분 동안 험담하더라”…이준석이 밝힌 ‘복국집 고함’ 내막은')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('155', '정치', '"기득권 핵심은 이재명"…"親明 험지출마" 역제안하는 非明')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('156', '정치', '한기호 국방위원장 분노 폭발… "김병주 날이 갈수록 왜 거짓말만 자꾸 하냐"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('157', '정치', ' 대통령 한마디에···‘예산도 안 잡힌 사업’ 졸속 추진')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('158', '정치', '신원식 국방부 장관의 테슬라 150주, 백지신탁될까')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('159', '정치', '금태섭 “이준석 곧 만날 것 …금요연석회의? 신당으로 가야”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('160', '정치', '민주 "北해킹에 국정원 공세적 조치, 컨트롤타워 다 안돼…정보활동 폐지가 개혁"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('161', '정치', '직무유기 고발에도 당당한 김용원 "위원장이 인권위 병들게 해"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('162', '정치', '노봉법·방송법 표결 D-1, 필리버스터 앞두고 여야 ‘전운’')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('163', '정치', '독립운동단체들 "육사 홍범도 흉상·독립영웅실 철거 백지화하라"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('164', '정치', '어느날 미국서 온 편지 "제 이름은 강춘강, K방산에 13억 써달라"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('165', '정치', '비명계 신당설" 의식했나…野, 의원 전원에 "불출마 확인서" 공문')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('166', '정치', '尹-朴 회동에…박지원 "총선 다가오니 급했나"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('167', '정치', '"조용히 좀 합시다" 이준석이 직접 밝힌 "복국집 신경전"의 전말')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('168', '정치', '대법원장 후보자에 조희대...대법관 때 "박근혜 뇌물죄 불성립"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('169', '정치', '홍준표 "대통령, 호가호위 이용 세력 깨닫고 최근엔 멀리하고 있을것"(종합)')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('170', '정치', '첫 상견례서 인요한 "도와달라" 홍준표 "듣보잡들 너무 설쳐"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('171', '정치', '용산·내각 출마 "러시"…與 총선기획단 "밀실 공천 없다"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('172', '정치', '만장일치로 ‘이동관 탄핵’ 추진하는 민주당…한동훈 장관은?')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('173', '정치', '중진 난 자리에 대통령실 참모들?···“혁신 코스프레하나” 당내 비판')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('174', '정치', '인요한, 홍준표 회동에 "거침없는 분…많은 말씀 생각해볼 것"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('175', '정치', '與 허은아 "洪, 맞는말 대잔치…내년 총선 후 내부총질 누가했는지 판가름"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('176', '정치', '민주, 이동관 탄핵 당론 발의 유보…"내일 의총서 결론"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('177', '정치', '여당 총선기획단 출범…""현역 20% 공천 배제" 논의"(종합)')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('178', '정치', '김병수 김포시장 "서울 편입, 총선용 아니다" 강조')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('179', '정치', ' 이재명, 총선 인재 발굴·영입 나서...홍준표 "이준석, 안 돌아올 것"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('180', '정치', '尹 대통령, 새 대법원장 후보에 조희대 전 대법관 지명')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('181', '정치', '여야 지도부는 조용…물밑에서만 다급한 "선거제 개편"')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('182', '정치', '여야, 본회의 격돌 예고…인요한·홍준표 회동')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('183', '정치', '조국·이준석 신당은 좀"…선거제 회귀에 힘 합치는 거대 양당?')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('184', '정치', '이준석-안철수 점심 먹다 고함 · 신경전')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('185', '정치', '홍준표 “박근혜 탄핵때 親朴 먼저 탈출…親尹도 그럴 것”')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('186', '정치', '윤대통령, 대법원장 후보자로 조희대 전 대법관 지명')
INSERT INTO test_news(news_id, cate_id, title) VALUES ('187', '정치', ' "도와주세요" 부탁에 홍준표 "듣보잡들 때문에 싫어!"…인요한 면전에 쏟아낸 "작심 쓴소리"')