In [ ]:
! pip3 install newspaper3k

In [ ]:
!pip install selenium
!pip install webdriver_manager
!pip install summa
!pip install textrankr
!pip install krwordrank

In [ ]:
!pip install koNLPy

In [ ]:
!pip3 install implicit

In [ ]:
!pip3 install nodeml

In [26]:
!pip install sklearn

Collecting sklearn
  Downloading sklearn-0.0.post11.tar.gz (3.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package

      If the previous advice does not cover your use case, feel free to report it at
      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [27]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import CountVectorizer

In [16]:

article_data = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\article.csv", encoding='cp949')

article_data

,category,title,content,views
0,정치,홍준표 곧 정계 빅뱅 올 것···나라도 살아야겠다는 엑소더스 친윤부터 퍼질지도,홍준표 대구시장은 곧 정계 빅뱅이 올 것으로 보인다라며 잘 대처하기를 바란다고 경고...,0
1,정치,北 성공한 11월18일 미사일공업절’로그날 맞춰 도발 감행’ 우려도,한·미·일 군사협력에 “핵전쟁 발발·3차대전 이어진다” 겁박북한이 11월 18일을 ...,0
2,정치,동앵과 뉴스터디“영남 스타 수도권으로” 발칵 뒤집힌 국민의힘,안녕하세요 동앵과 뉴스터디 동정민 앵커입니다국민의힘 혁신위원회가 출범하고 시끌시끌합...,0
3,정치,민주당 이탄희 조선일보가 두려워하는 건 ○○정치,판사 출신 이탄희 의원 선거법 퇴행엔 “직을 걸고 막겠다”양당 구도를 깨자며 연합 ...,0
4,정치,정청래 尹 직격 대통령 잘못 뽑아 온 국민이 고생이대로 가면 나라 큰일 날 듯,정청래 더불어민주당 최고위원이 윤석열 정부를 비판하며 이재명 대표 중심으로 뭉친 민...,0
...,...,...,...,...
1394,연예,판타지 보이즈 신곡 안무 시안 영상으로 글로벌 영향력 확실히 입증,그룹 판타지 보이즈김규래·홍성민·오현태·이한빈·링치·강민서·히카리·소울·...,0
1395,연예,위대한 가이드’ 골동품 투어로 인생역전 성공할까,위대한 가이드’ 멤버들이 골동품 시장에서 숨은 보석 찾기에 나선다6일 방송되는 에브...,0
1396,연예,무인도의 디바 박은빈 차학연에 꽃다발 전달받고 눈물 펑펑,무인도의 디바’ 박은빈에게 의문의 꽃다발이 도착한다토일드라마무인도의 디바’극본 박...,0
1397,연예,충주시장 5만원 넘는 선물 덥석 받았다가 진땀충주맨은 바로 거절,서울뉴스1 조길형 충주시장이 예능 프로그램에 출연해 17만원 상당의 옷을 선물받...,0
1398,연예,최강야구 투수 이대호 타자 김선우 마침내 성사된 세기의 대결,“열 타석을 해도 쉽지 않다”오직 최강야구’에서만 볼 수 있는 세기의 대결이 펼쳐진...,0

In [47]:
# 임의로 조회수 설정 -> 나중에 활용 시 random대신 실제 조회수 삽입
data = pd.DataFrame(article_data)
for i in range(len(article_data)):
    data.loc[i, 'views'] = np.random.randint(0, 10000)

data.to_csv("views.csv")

In [57]:
# 회원 로그
log = pd.DataFrame(article_data)
for i in range(len(article_data)):
    log.loc[i, 'views'] = np.random.randint(1, 20)

log.rename(columns={'views' : 'user'}, inplace=True)
log.drop('content', axis=1, inplace=True)
log.to_csv('log.csv')

<h3>테스트 블록은 여기서부터 수행</h3>

In [226]:
# view_data = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\views.csv", encoding='cp949')
# log_data = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\log.csv", encoding='cp949')
view_data = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\test_v.csv", encoding='cp949')
log_data= pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\test_l.csv", encoding='cp949')

# usr_article_views = pd.merge(log_data, view_data, on="title")
usr_article_views = pd.DataFrame(log_data)

In [227]:
# 회원별 조회한 기사 피벗 테이블화
usr_article_views = usr_article_views.pivot_table(index='user', columns='title', aggfunc=len, fill_value=0)
usr_article_views

title  it7  과학3  과학6  사회4  사회5  연예10  연예11  연예12  연예2  정치1  정치8  정치9
user
1        0    0    0    1    1     0     0     0    0    1    1    1
2        0    0    0    1    0     0     0     0    0    0    1    1
3        1    0    1    1    0     0     0     0    1    0    0    0
4        1    1    1    0    0     0     0     0    0    0    0    0
5        0    1    0    0    0     0     0     0    1    1    0    0
6        0    1    0    0    1     0     0     0    1    1    0    0
7        0    0    0    1    1     0     0     0    0    1    1    1
8        0    0    0    0    0     0     0     0    0    1    1    1
9        0    0    0    1    0     0     0     0    2    0    0    0
10       0    0    0    1    2     0     0     0    0    0    0    0
11       0    0    0    0    0     1     1     0    1    0    0    0
12       0    0    0    0    0     1     1     1    1    0    0    0
13       0    0    0    0    0     1     1     1    1    0    0    0
14       0    0    0    0    0     1     1     1    1    0    0    0
15       1    1    0    0    0     0     0     0    0    0    0    0
16       0    0    1    1    0     0     0     0    0    0    0    0
17       0    1    0    0    0     0     0     0    0    1    0    0
18       0    1    1    0    0     0     0     0    0    0    0    0
19       0    1    1    0    0     0     0     0    0    1    1    1
20       0    1    1    0    0     0     0     0    0    0    1    1

In [228]:
from sklearn.metrics.pairwise import cosine_similarity
# 회원간 유사도 판별
user_similarity = cosine_similarity(usr_article_views)
user_similarity

array([[1.        , 0.77459667, 0.2236068 , 0.        , 0.25819889,
        0.4472136 , 1.        , 0.77459667, 0.2       , 0.6       ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.31622777, 0.31622777, 0.        , 0.6       , 0.4472136 ],
       [0.77459667, 1.        , 0.28867513, 0.        , 0.        ,
        0.        , 0.77459667, 0.66666667, 0.25819889, 0.25819889,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.40824829, 0.        , 0.        , 0.51639778, 0.57735027],
       [0.2236068 , 0.28867513, 1.        , 0.57735027, 0.28867513,
        0.25      , 0.2236068 , 0.        , 0.67082039, 0.2236068 ,
        0.28867513, 0.25      , 0.25      , 0.25      , 0.35355339,
        0.70710678, 0.        , 0.35355339, 0.2236068 , 0.25      ],
       [0.        , 0.        , 0.57735027, 1.        , 0.33333333,
        0.28867513, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.81649658,
        0.40824829, 0.40824829, 0.81649658, 0.51639778, 0.57735027],
       [0.25819889, 0.        , 0.28867513, 0.33333333, 1.        ,
        0.8660254 , 0.25819889, 0.33333333, 0.51639778, 0.        ,
        0.33333333, 0.28867513, 0.28867513, 0.28867513, 0.40824829,
        0.        , 0.81649658, 0.40824829, 0.51639778, 0.28867513],
       [0.4472136 , 0.        , 0.25      , 0.28867513, 0.8660254 ,
        1.        , 0.4472136 , 0.28867513, 0.4472136 , 0.4472136 ,
        0.28867513, 0.25      , 0.25      , 0.25      , 0.35355339,
        0.        , 0.70710678, 0.35355339, 0.4472136 , 0.25      ],
       [1.        , 0.77459667, 0.2236068 , 0.        , 0.25819889,
        0.4472136 , 1.        , 0.77459667, 0.2       , 0.6       ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.31622777, 0.31622777, 0.        , 0.6       , 0.4472136 ],
       [0.77459667, 0.66666667, 0.        , 0.        , 0.33333333,
        0.28867513, 0.77459667, 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.40824829, 0.        , 0.77459667, 0.57735027],
       [0.2       , 0.25819889, 0.67082039, 0.        , 0.51639778,
        0.4472136 , 0.2       , 0.        , 1.        , 0.2       ,
        0.51639778, 0.4472136 , 0.4472136 , 0.4472136 , 0.        ,
        0.31622777, 0.        , 0.        , 0.        , 0.        ],
       [0.6       , 0.25819889, 0.2236068 , 0.        , 0.        ,
        0.4472136 , 0.6       , 0.        , 0.2       , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.31622777, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.28867513, 0.        , 0.33333333,
        0.28867513, 0.        , 0.        , 0.51639778, 0.        ,
        1.        , 0.8660254 , 0.8660254 , 0.8660254 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        , 0.28867513,
        0.25      , 0.        , 0.        , 0.4472136 , 0.        ,
        0.8660254 , 1.        , 1.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        , 0.28867513,
        0.25      , 0.        , 0.        , 0.4472136 , 0.        ,
        0.8660254 , 1.        , 1.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        , 0.28867513,
        0.25      , 0.        , 0.        , 0.4472136 , 0.        ,
        0.8660254 , 1.        , 1.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.35355339, 0.81649658, 0.40824829,
        0.35355339, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.5       , 0.5       , 0.31622777, 0.35355339],
       [0.31622777, 0.40824829, 0.70710678, 0.40824829, 0.        ,
        0.        , 0.31622777, 0.        , 0.31622777, 0.31622777,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.5       , 0.31622777, 0.35355339],
       [0.31622777, 0.        , 0.        , 0.40824829, 0.81649658,
        0.70710678, 0.31622777, 0.40824829, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.5       ,
        0.        , 1.        , 0.5       , 0.63245553, 0.35355339],
       [0.        , 0.        , 0.35355339, 0.81649658, 0.40824829,
        0.35355339, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.5       ,
        0.5       , 0.5       , 1.        , 0.63245553, 0.70710678],
       [0.6       , 0.51639778, 0.2236068 , 0.51639778, 0.51639778,
        0.4472136 , 0.6       , 0.77459667, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.31622777,
        0.31622777, 0.63245553, 0.63245553, 1.        , 0.89442719],
       [0.4472136 , 0.57735027, 0.25      , 0.57735027, 0.28867513,
        0.25      , 0.4472136 , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.35355339,
        0.35355339, 0.35355339, 0.70710678, 0.89442719, 1.        ]])

In [257]:
def recommend(target): # target번 사용자에게 추천하는 경우
    # target 사용자와 유사한 사용자 탐색
    similar_users = user_similarity[target - 1]
    similar_users_indexes = similar_users.argsort()[::-1]

    # 대상 사용자가 아직 시청하지 않은 기사 중에서 유사한 사용자가 시청한 기사 추천
    recommended_articles = {}
    flag = 0
    for user_index in similar_users_indexes:
        if user_index == target - 1:
            continue  # 자기 자신은 제외
        tmp = []
        score = 0
        for a_title in usr_article_views.columns:
            if usr_article_views.at[user_index + 1, a_title] == 1:
                # 겹칠떄마다 cnt ++ 다른 모든 기사에 점수 +cnt 
                if usr_article_views.at[target, a_title] == 1: # 겹치면 점수 +1
                    score += 1
                else: # 안겹치면 tmp에 추가
                    tmp.append(a_title)
        
        for i in tmp:
            if i not in recommended_articles:
                recommended_articles[i] = score
            else:
                recommended_articles[i] += score

    amount = 3 # 추천할 기사 갯수 설정
    res = dict(sorted(recommended_articles.items(), key=lambda x : -x[1]))
    print("" + str(target) + "번 회원님, 다음 기사를 추천합니다.")
    print(list(res.keys())[:amount]) 
    print("" + str(target) + "번 회원과 유사도가 높은 회원 목록(내림차순)")
    for i in similar_users_indexes:
        if i + 1 == target:continue
        print(i + 1, end=" ")

<h2>각 회원별 읽은 기사 예시 데이터</h2>
1번 -> 정치1 정치8 사회4 사회5 정치9<br>
2번 -> 정치8 사회4 정치9 -----> 예상 추천: 정치1 사회 5<br>
3번 -> 연예2 사회4 과학6 it7<br>
4번 -> 과학3 과학6 it7<br>
5번 -> 정치1 연예2 과학3 -----> 예상 추천 : 사회5<br>
6번 -> 정치1 연예2 과학3 사회5<br>
7번 -> 정치1 정치8 사회4 정치9 사회5<br>
8번 -> 정치1 정치8 정치9<br>
9번 -> 연예2 사회4 사회5<br>
10번 -> 연예2 사회4 사회5<br>
11번 -> 연예2 연예10 연예11 -----> 예상 추천 : 연예12<br>
12번 -> 연예2 연예10 연예11 연예12<br>
13번 -> 연예2 연예10 연예11 연예12<br>
14번 -> 연예2 연예10 연예11 연예12<br>
15번 -> 과학3 it7 -----> 예상 추천 : 과학6<br>
16번 -> 과학6 사회4<br>
17번 -> 정치1 과학3<br>
18번 -> 과학3 과학6 -----> 예상 추천 : it7<br>
19번 -> 정치1 정치8 정치9 과학3 과학6<br>
20번 -> 정치9 정치8 과학3 과학6 -----> 예상 추천 : 정치1<br>

In [259]:
n = int(input("당신은 몇번 회원입니까?"))
recommend(n)

4번 회원님, 다음 기사를 추천합니다.
['정치1', '정치8', '정치9']
4번 회원과 유사도가 높은 회원 목록(내림차순)
18 15 20 3 19 17 16 5 6 7 2 10 8 9 11 12 13 14 1