In [16]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import random

<h2> 선호 카테고리 테이블 전처리</h2>
<p>select * from preference</p>

In [7]:
pref = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\test2_preference.csv", index_col='mem_id', encoding='cp949')
pref

       cate_id
mem_id
1           경제
1           사회
1           정치
2           경제
2           사회
...        ...
249         사회
249         연예
250         경제
250         사회
250         연예

[750 rows x 1 columns]

In [22]:
# 각 회원 별 무작위 선호 카테고리 난수 지정 -> 테스트 회원은 250명으로 임시 설정
arr = []
for i in range(250):
    tmp = random.sample(range(7), 3)
    arr.append(tmp[0])
    arr.append(tmp[1])
    arr.append(tmp[2])

print(arr)

[6, 2, 0, 1, 6, 3, 5, 4, 2, 4, 0, 5, 1, 4, 2, 3, 4, 1, 3, 5, 4, 2, 3, 1, 1, 6, 4, 5, 4, 3, 3, 4, 0, 1, 6, 4, 4, 0, 1, 5, 2, 1, 1, 5, 4, 3, 1, 0, 1, 4, 5, 3, 4, 6, 1, 6, 4, 6, 1, 0, 4, 6, 0, 1, 2, 0, 2, 6, 4, 5, 0, 3, 4, 6, 1, 5, 6, 0, 1, 6, 0, 0, 6, 4, 1, 5, 3, 6, 5, 4, 2, 6, 3, 5, 1, 2, 2, 4, 5, 1, 2, 6, 1, 3, 0, 2, 6, 0, 0, 6, 1, 2, 1, 3, 4, 6, 1, 5, 1, 0, 0, 2, 1, 6, 1, 4, 6, 1, 4, 6, 2, 0, 1, 0, 6, 6, 3, 1, 3, 6, 0, 5, 3, 0, 3, 2, 5, 3, 4, 5, 5, 6, 1, 0, 3, 6, 3, 4, 6, 5, 6, 3, 1, 5, 6, 2, 6, 5, 5, 0, 6, 3, 1, 4, 1, 5, 4, 4, 0, 3, 5, 1, 6, 5, 3, 4, 0, 3, 1, 6, 2, 5, 4, 3, 6, 3, 0, 1, 2, 3, 1, 1, 6, 0, 1, 6, 2, 2, 6, 4, 6, 4, 5, 3, 1, 2, 3, 4, 1, 1, 4, 0, 2, 3, 5, 1, 0, 6, 1, 6, 2, 0, 2, 3, 3, 1, 5, 3, 2, 1, 5, 2, 3, 2, 1, 3, 4, 6, 0, 4, 0, 5, 0, 3, 5, 4, 0, 3, 4, 6, 5, 1, 3, 5, 5, 3, 1, 1, 3, 5, 6, 4, 2, 5, 6, 3, 2, 1, 5, 0, 6, 2, 5, 4, 3, 0, 3, 5, 1, 5, 2, 1, 4, 3, 5, 0, 6, 5, 4, 0, 6, 0, 4, 2, 1, 3, 5, 2, 3, 2, 6, 3, 0, 2, 6, 2, 3, 4, 6, 1, 2, 4, 1, 5, 6, 0, 1, 5, 4, 3, 5, 2, 3, 5, 2, 1, 0, 2, 4, 1, 2, 6, 1, 0, 4, 3, 1, 2, 4, 5, 2, 4, 1, 2, 4, 0, 6, 6, 5, 4, 5, 1, 4, 0, 1, 6, 4, 2, 6, 0, 6, 1, 5, 3, 6, 6, 2, 5, 3, 1, 4, 4, 0, 5, 4, 2, 1, 2, 3, 5, 5, 2, 1, 6, 3, 4, 6, 1, 5, 6, 0, 1, 6, 2, 5, 2, 6, 4, 0, 3, 5, 6, 5, 2, 2, 6, 1, 4, 2, 5, 1, 2, 0, 5, 6, 1, 2, 0, 3, 4, 5, 0, 1, 0, 4, 2, 5, 1, 0, 6, 2, 0, 6, 3, 3, 1, 6, 5, 4, 6, 5, 2, 0, 5, 3, 0, 0, 4, 3, 4, 1, 2, 5, 4, 0, 6, 5, 2, 1, 0, 2, 3, 5, 0, 5, 4, 6, 5, 6, 1, 0, 5, 4, 1, 5, 4, 1, 4, 5, 2, 4, 5, 6, 0, 1, 6, 3, 4, 4, 5, 2, 4, 5, 1, 1, 3, 2, 0, 3, 2, 1, 3, 6, 3, 4, 0, 5, 6, 1, 4, 5, 6, 0, 4, 5, 2, 0, 4, 1, 0, 6, 5, 3, 6, 5, 1, 0, 6, 3, 2, 6, 2, 0, 4, 3, 1, 3, 0, 2, 5, 0, 4, 6, 1, 3, 2, 0, 4, 0, 3, 2, 4, 6, 1, 6, 0, 4, 4, 3, 5, 6, 1, 5, 4, 6, 0, 1, 5, 6, 2, 1, 0, 1, 5, 0, 4, 5, 0, 1, 5, 4, 1, 2, 3, 3, 0, 4, 3, 0, 6, 6, 5, 0, 2, 4, 5, 0, 3, 6, 4, 6, 3, 6, 0, 5, 2, 3, 5, 1, 3, 2, 1, 0, 2, 4, 6, 3, 4, 6, 5, 6, 1, 2, 3, 5, 0, 3, 5, 4, 6, 2, 0, 4, 3, 1, 4, 5, 1, 2, 3, 5, 4, 2, 3, 2, 4, 0, 6, 5, 2, 3, 6, 5, 4, 0, 1, 5, 2, 4, 6, 1, 4, 0, 1, 6, 0, 5, 6, 6, 3, 5, 2, 4, 1, 3, 1, 6, 2, 4, 1, 6, 3, 1, 2, 6, 3, 2, 5, 3, 0, 1, 4, 3, 1, 5, 1, 3, 2, 1, 2, 4, 0, 2, 6, 2, 0, 4, 0, 1, 6, 3, 6, 1, 6, 3, 2, 4, 3, 1, 0, 2, 5, 6, 0, 4, 0, 4, 1, 2, 0, 5, 3, 0, 1, 3, 5, 6, 0, 4, 5]

In [23]:
# arr에 배정된 숫자에 따라 cate에서 인덱스로 카테고리 지정
cate = ['정치', '연예', '경제', '사회', '생활/문화', '세계', 'IT/과학']
pref['cate_id'] = [cate[a] for a in arr]
pref

       cate_id
mem_id
1        IT/과학
1           경제
1           정치
2           연예
2        IT/과학
...        ...
249         세계
249      IT/과학
250         정치
250      생활/문화
250         세계

[750 rows x 1 columns]

In [24]:
pref.to_csv("C:\\Users\\PC\\Desktop\\library_test\\test2_preference.csv", encoding='cp949')

<h2>회원 별 읽은 기사 무작위 배정</h2>
<p>select * from user_log(?)</p>
--> 아직 DB에 로그 테이블 없음 -> 만들어야 함

In [27]:
news = pd.read_csv("C:\\Users\\PC\\Desktop\\library_test\\test2_news.csv", index_col='news_id', encoding='cp949')
news
# 기사 제목, 아이디, 카테고리만 가져옴

        cate_id                                  title
news_id
0            정치     이탈리아 지지표 흡수는 기본… 중립 성향 표심 잡는 게 관건
1            정치  이준석 “영남 정치인들 편하게 놔두지 않겠다”…영남 신당 추진 시사
2            정치   주호영 “서울 갈 일 없다”…이준석 “대구에서 어려운 승부할 것”
3            정치   28억 재산 누락' 김대기 "단순 실수"…야당 "대국민 사과해야"
4            정치       與 핵심, '거취 압박' 대응 자제...내부선 불만 기류도
...         ...                                    ...
1389         연예                            김영,'훈훈한 미소'
1390         연예                          신연서,'소중한 강아지'
1391         연예                            최훈재,'나도 찰칵'
1392         연예                            백서빈,'깔끔 청년'
1393         연예                           구상범 감독,'볼하트'

[1394 rows x 2 columns]

In [58]:
# 250명이 1394개의 기사중 몇개를 무작위로 고르는 로그 16000개
data = {
    'mem_id': np.random.randint(1, 251, size=16000),
    'news_id': np.random.randint(1, 1394, size=16000)
}

log1 = pd.DataFrame(data)  # 난수로 회원-기사 배정
log1 = pd.merge(log1, news, on='news_id') # 카테고리와 제목 가져오기
log1.to_csv("C:\\Users\\PC\\Desktop\\library_test\\test2_log1.csv", encoding='cp949')

[175.000000000000]